/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import { BaseResource, CloudError, AzureServiceClientOptions } from "ms-rest-azure-js";
import * as msRest from "ms-rest-js";

export { BaseResource, CloudError };


/**
 * @interface
 * An interface representing ArtifactParameterProperties.
 * Properties of an artifact parameter.
 *
 */
export interface ArtifactParameterProperties {
  /**
   * @member {string} [name] The name of the artifact parameter.
   */
  name?: string;
  /**
   * @member {string} [value] The value of the artifact parameter.
   */
  value?: string;
}

/**
 * @interface
 * An interface representing ArtifactInstallProperties.
 * Properties of an artifact.
 *
 */
export interface ArtifactInstallProperties {
  /**
   * @member {string} [artifactId] The artifact's identifier.
   */
  artifactId?: string;
  /**
   * @member {ArtifactParameterProperties[]} [parameters] The parameters of the
   * artifact.
   */
  parameters?: ArtifactParameterProperties[];
}

/**
 * @interface
 * An interface representing ApplyArtifactsRequest.
 * Request body for applying artifacts to a virtual machine.
 *
 */
export interface ApplyArtifactsRequest {
  /**
   * @member {ArtifactInstallProperties[]} [artifacts] The list of artifacts to
   * apply.
   */
  artifacts?: ArtifactInstallProperties[];
}

/**
 * @interface
 * An interface representing ArmTemplateInfo.
 * Information about a generated ARM template.
 *
 */
export interface ArmTemplateInfo {
  /**
   * @member {any} [template] The template's contents.
   */
  template?: any;
  /**
   * @member {any} [parameters] The parameters of the ARM template.
   */
  parameters?: any;
}

/**
 * @interface
 * An interface representing Artifact.
 * An artifact.
 *
 * @extends BaseResource
 */
export interface Artifact extends BaseResource {
  /**
   * @member {string} [title] The title of the artifact.
   */
  title?: string;
  /**
   * @member {string} [description] The description of the artifact.
   */
  description?: string;
  /**
   * @member {string} [filePath] The file path of the artifact.
   */
  filePath?: string;
  /**
   * @member {string} [icon] The icon of the artifact.
   */
  icon?: string;
  /**
   * @member {string} [targetOsType] Gets or sets the type of the target os.
   */
  targetOsType?: string;
  /**
   * @member {any} [parameters] The parameters of the artifact.
   */
  parameters?: any;
  /**
   * @member {string} [id] The identifier of the resource.
   */
  id?: string;
  /**
   * @member {string} [name] The name of the resource.
   */
  name?: string;
  /**
   * @member {string} [type] The type of the resource.
   */
  type?: string;
  /**
   * @member {string} [location] The location of the resource.
   */
  location?: string;
  /**
   * @member {{ [propertyName: string]: string }} [tags] The tags of the
   * resource.
   */
  tags?: { [propertyName: string]: string };
}

/**
 * @interface
 * An interface representing ArtifactDeploymentStatusProperties.
 * Properties of an artifact deployment.
 *
 */
export interface ArtifactDeploymentStatusProperties {
  /**
   * @member {string} [deploymentStatus] The deployment status of the artifact.
   */
  deploymentStatus?: string;
  /**
   * @member {number} [artifactsApplied] The total count of the artifacts that
   * were successfully applied.
   */
  artifactsApplied?: number;
  /**
   * @member {number} [totalArtifacts] The total count of the artifacts that
   * were tentatively applied.
   */
  totalArtifacts?: number;
}

/**
 * @interface
 * An interface representing ArtifactSource.
 * Properties of an artifact source.
 *
 * @extends BaseResource
 */
export interface ArtifactSource extends BaseResource {
  /**
   * @member {string} [displayName] The display name of the artifact source.
   */
  displayName?: string;
  /**
   * @member {string} [uri] The URI of the artifact source.
   */
  uri?: string;
  /**
   * @member {SourceControlType} [sourceType] The type of the artifact source.
   * Possible values include: 'VsoGit', 'GitHub'
   */
  sourceType?: SourceControlType;
  /**
   * @member {string} [folderPath] The folder path of the artifact source.
   */
  folderPath?: string;
  /**
   * @member {string} [branchRef] The branch reference of the artifact source.
   */
  branchRef?: string;
  /**
   * @member {string} [securityToken] The security token of the artifact
   * source.
   */
  securityToken?: string;
  /**
   * @member {EnableStatus} [status] The status of the artifact source.
   * Possible values include: 'Enabled', 'Disabled'
   */
  status?: EnableStatus;
  /**
   * @member {string} [provisioningState] The provisioning status of the
   * resource.
   */
  provisioningState?: string;
  /**
   * @member {string} [id] The identifier of the resource.
   */
  id?: string;
  /**
   * @member {string} [name] The name of the resource.
   */
  name?: string;
  /**
   * @member {string} [type] The type of the resource.
   */
  type?: string;
  /**
   * @member {string} [location] The location of the resource.
   */
  location?: string;
  /**
   * @member {{ [propertyName: string]: string }} [tags] The tags of the
   * resource.
   */
  tags?: { [propertyName: string]: string };
}

/**
 * @interface
 * An interface representing CostPerDayProperties.
 * The per-day properties of a cost item.
 *
 */
export interface CostPerDayProperties {
  /**
   * @member {Date} [date] The date of the cost item.
   */
  date?: Date;
  /**
   * @member {number} [cost] The cost of the cost item.
   */
  cost?: number;
  /**
   * @member {CostPropertyType} [costType] The type of the cost. Possible
   * values include: 'Unavailable', 'Reported', 'Projected'
   */
  costType?: CostPropertyType;
}

/**
 * @interface
 * An interface representing Cost.
 * A cost item.
 *
 * @extends BaseResource
 */
export interface Cost extends BaseResource {
  /**
   * @member {string} [currencyCode] The currency code of the cost.
   */
  currencyCode?: string;
  /**
   * @member {CostPerDayProperties[]} [costs] The per-day costs items of the
   * cost.
   */
  costs?: CostPerDayProperties[];
  /**
   * @member {string} [id] The identifier of the resource.
   */
  id?: string;
  /**
   * @member {string} [name] The name of the resource.
   */
  name?: string;
  /**
   * @member {string} [type] The type of the resource.
   */
  type?: string;
  /**
   * @member {string} [location] The location of the resource.
   */
  location?: string;
  /**
   * @member {{ [propertyName: string]: string }} [tags] The tags of the
   * resource.
   */
  tags?: { [propertyName: string]: string };
}

/**
 * @interface
 * An interface representing VMCostProperties.
 */
export interface VMCostProperties {
  /**
   * @member {string} [name]
   */
  name?: string;
  /**
   * @member {string} [resourceGroupName]
   */
  resourceGroupName?: string;
  /**
   * @member {number} [cost]
   */
  cost?: number;
}

/**
 * @interface
 * An interface representing CostInsight.
 * @extends BaseResource
 */
export interface CostInsight extends BaseResource {
  /**
   * @member {string} [currencyCode]
   */
  currencyCode?: string;
  /**
   * @member {VMCostProperties[]} [vmCosts]
   */
  vmCosts?: VMCostProperties[];
  /**
   * @member {string} [provisioningState] The provisioning status of the
   * resource.
   */
  provisioningState?: string;
  /**
   * @member {string} [id] The identifier of the resource.
   */
  id?: string;
  /**
   * @member {string} [name] The name of the resource.
   */
  name?: string;
  /**
   * @member {string} [type] The type of the resource.
   */
  type?: string;
  /**
   * @member {string} [location] The location of the resource.
   */
  location?: string;
  /**
   * @member {{ [propertyName: string]: string }} [tags] The tags of the
   * resource.
   */
  tags?: { [propertyName: string]: string };
}

/**
 * @interface
 * An interface representing WindowsOsInfo.
 * Information about a Windows OS.
 *
 */
export interface WindowsOsInfo {
  /**
   * @member {WindowsOsState} [windowsOsState] The state of the Windows OS.
   * Possible values include: 'NonSysprepped', 'SysprepRequested',
   * 'SysprepApplied'
   */
  windowsOsState?: WindowsOsState;
}

/**
 * @interface
 * An interface representing LinuxOsInfo.
 * Information about a Linux OS.
 *
 */
export interface LinuxOsInfo {
  /**
   * @member {LinuxOsState} [linuxOsState] The state of the Linux OS. Possible
   * values include: 'NonDeprovisioned', 'DeprovisionRequested',
   * 'DeprovisionApplied'
   */
  linuxOsState?: LinuxOsState;
}

/**
 * @interface
 * An interface representing CustomImagePropertiesFromVm.
 * Properties for creating a custom image from a virtual machine.
 *
 */
export interface CustomImagePropertiesFromVm {
  /**
   * @member {string} [sourceVmId] The source vm identifier.
   */
  sourceVmId?: string;
  /**
   * @member {boolean} [sysPrep] Indicates whether sysprep has been run on the
   * VHD.
   */
  sysPrep?: boolean;
  /**
   * @member {WindowsOsInfo} [windowsOsInfo] The Windows OS information of the
   * VM.
   */
  windowsOsInfo?: WindowsOsInfo;
  /**
   * @member {LinuxOsInfo} [linuxOsInfo] The Linux OS information of the VM.
   */
  linuxOsInfo?: LinuxOsInfo;
}

/**
 * @interface
 * An interface representing CustomImagePropertiesCustom.
 * Properties for creating a custom image from a VHD.
 *
 */
export interface CustomImagePropertiesCustom {
  /**
   * @member {string} [imageName] The image name.
   */
  imageName?: string;
  /**
   * @member {boolean} [sysPrep] Indicates whether sysprep has been run on the
   * VHD.
   */
  sysPrep?: boolean;
}

/**
 * @interface
 * An interface representing CustomImage.
 * A custom image.
 *
 * @extends BaseResource
 */
export interface CustomImage extends BaseResource {
  /**
   * @member {CustomImagePropertiesFromVm} [vm]
   */
  vm?: CustomImagePropertiesFromVm;
  /**
   * @member {CustomImagePropertiesCustom} [vhd] The VHD from which the image
   * is to be created.
   */
  vhd?: CustomImagePropertiesCustom;
  /**
   * @member {string} [description] The description of the custom image.
   */
  description?: string;
  /**
   * @member {CustomImageOsType} [osType] The OS type of the custom image.
   * Possible values include: 'Windows', 'Linux', 'None'
   */
  osType?: CustomImageOsType;
  /**
   * @member {string} [author] The author of the custom image.
   */
  author?: string;
  /**
   * @member {Date} [creationDate] The creation date of the custom image.
   */
  creationDate?: Date;
  /**
   * @member {string} [provisioningState] The provisioning status of the
   * resource.
   */
  provisioningState?: string;
  /**
   * @member {string} [id] The identifier of the resource.
   */
  id?: string;
  /**
   * @member {string} [name] The name of the resource.
   */
  name?: string;
  /**
   * @member {string} [type] The type of the resource.
   */
  type?: string;
  /**
   * @member {string} [location] The location of the resource.
   */
  location?: string;
  /**
   * @member {{ [propertyName: string]: string }} [tags] The tags of the
   * resource.
   */
  tags?: { [propertyName: string]: string };
}

/**
 * @interface
 * An interface representing DayDetails.
 * Properties of a daily schedule.
 *
 */
export interface DayDetails {
  /**
   * @member {string} [time]
   */
  time?: string;
}

/**
 * @interface
 * An interface representing EvaluatePoliciesProperties.
 * Properties for evaluating a policy set.
 *
 */
export interface EvaluatePoliciesProperties {
  /**
   * @member {string} [factName] The fact name.
   */
  factName?: string;
  /**
   * @member {string} [factData] The fact data.
   */
  factData?: string;
  /**
   * @member {string} [valueOffset] The value offset.
   */
  valueOffset?: string;
}

/**
 * @interface
 * An interface representing EvaluatePoliciesRequest.
 * Request body for evaluating a policy set.
 *
 */
export interface EvaluatePoliciesRequest {
  /**
   * @member {EvaluatePoliciesProperties[]} [policies] Policies to evaluate.
   */
  policies?: EvaluatePoliciesProperties[];
}

/**
 * @interface
 * An interface representing PolicyViolation.
 * Policy violation.
 *
 */
export interface PolicyViolation {
  /**
   * @member {string} [code] The code of the policy violation.
   */
  code?: string;
  /**
   * @member {string} [message] The message of the policy violation.
   */
  message?: string;
}

/**
 * @interface
 * An interface representing PolicySetResult.
 * Result of a policy set evaluation.
 *
 */
export interface PolicySetResult {
  /**
   * @member {boolean} [hasError] A value indicating whether this policy set
   * evaluation has discovered violations.
   */
  hasError?: boolean;
  /**
   * @member {PolicyViolation[]} [policyViolations] The list of policy
   * violations.
   */
  policyViolations?: PolicyViolation[];
}

/**
 * @interface
 * An interface representing EvaluatePoliciesResponse.
 * Response body for evaluating a policy set.
 *
 */
export interface EvaluatePoliciesResponse {
  /**
   * @member {PolicySetResult[]} [results] Results of evaluating a policy set.
   */
  results?: PolicySetResult[];
}

/**
 * @interface
 * An interface representing GalleryImageReference.
 * The reference information for an Azure Marketplace image.
 *
 */
export interface GalleryImageReference {
  /**
   * @member {string} [offer] The offer of the gallery image.
   */
  offer?: string;
  /**
   * @member {string} [publisher] The publisher of the gallery image.
   */
  publisher?: string;
  /**
   * @member {string} [sku] The SKU of the gallery image.
   */
  sku?: string;
  /**
   * @member {string} [osType] The OS type of the gallery image.
   */
  osType?: string;
  /**
   * @member {string} [version] The version of the gallery image.
   */
  version?: string;
}

/**
 * @interface
 * An interface representing LabVirtualMachine.
 * A virtual machine.
 *
 * @extends BaseResource
 */
export interface LabVirtualMachine extends BaseResource {
  /**
   * @member {string} [notes] The notes of the virtual machine.
   */
  notes?: string;
  /**
   * @member {string} [ownerObjectId] The object identifier of the owner of the
   * virtual machine.
   */
  ownerObjectId?: string;
  /**
   * @member {string} [createdByUserId] The object identifier of the creator of
   * the virtual machine.
   */
  createdByUserId?: string;
  /**
   * @member {string} [createdByUser] The email address of creator of the
   * virtual machine.
   */
  createdByUser?: string;
  /**
   * @member {string} [computeId] The resource identifier (Microsoft.Compute)
   * of the virtual machine.
   */
  computeId?: string;
  /**
   * @member {string} [customImageId] The custom image identifier of the
   * virtual machine.
   */
  customImageId?: string;
  /**
   * @member {string} [osType] The OS type of the virtual machine.
   */
  osType?: string;
  /**
   * @member {string} [size] The size of the virtual machine.
   */
  size?: string;
  /**
   * @member {string} [userName] The user name of the virtual machine.
   */
  userName?: string;
  /**
   * @member {string} [password] The password of the virtual machine
   * administrator.
   */
  password?: string;
  /**
   * @member {string} [sshKey] The SSH key of the virtual machine
   * administrator.
   */
  sshKey?: string;
  /**
   * @member {boolean} [isAuthenticationWithSshKey] A value indicating whether
   * this virtual machine uses an SSH key for authentication.
   */
  isAuthenticationWithSshKey?: boolean;
  /**
   * @member {string} [fqdn] The fully-qualified domain name of the virtual
   * machine.
   */
  fqdn?: string;
  /**
   * @member {string} [labSubnetName] The lab subnet name of the virtual
   * machine.
   */
  labSubnetName?: string;
  /**
   * @member {string} [labVirtualNetworkId] The lab virtual network identifier
   * of the virtual machine.
   */
  labVirtualNetworkId?: string;
  /**
   * @member {boolean} [disallowPublicIpAddress] Indicates whether the virtual
   * machine is to be created without a public IP address.
   */
  disallowPublicIpAddress?: boolean;
  /**
   * @member {ArtifactInstallProperties[]} [artifacts] The artifacts to be
   * installed on the virtual machine.
   */
  artifacts?: ArtifactInstallProperties[];
  /**
   * @member {ArtifactDeploymentStatusProperties} [artifactDeploymentStatus]
   * The artifact deployment status for the virtual machine.
   */
  artifactDeploymentStatus?: ArtifactDeploymentStatusProperties;
  /**
   * @member {GalleryImageReference} [galleryImageReference] The Microsoft
   * Azure Marketplace image reference of the virtual machine.
   */
  galleryImageReference?: GalleryImageReference;
  /**
   * @member {string} [provisioningState] The provisioning status of the
   * resource.
   */
  provisioningState?: string;
  /**
   * @member {string} [id] The identifier of the resource.
   */
  id?: string;
  /**
   * @member {string} [name] The name of the resource.
   */
  name?: string;
  /**
   * @member {string} [type] The type of the resource.
   */
  type?: string;
  /**
   * @member {string} [location] The location of the resource.
   */
  location?: string;
  /**
   * @member {{ [propertyName: string]: string }} [tags] The tags of the
   * resource.
   */
  tags?: { [propertyName: string]: string };
}

/**
 * @interface
 * An interface representing FormulaPropertiesFromVm.
 * Information about a VM from which a formula is to be created.
 *
 */
export interface FormulaPropertiesFromVm {
  /**
   * @member {string} [labVmId] The identifier of the VM from which a formula
   * is to be created.
   */
  labVmId?: string;
}

/**
 * @interface
 * An interface representing Formula.
 * A formula.
 *
 * @extends BaseResource
 */
export interface Formula extends BaseResource {
  /**
   * @member {string} [description] The description of the formula.
   */
  description?: string;
  /**
   * @member {string} [author] The author of the formula.
   */
  author?: string;
  /**
   * @member {string} [osType] The OS type of the formula.
   */
  osType?: string;
  /**
   * @member {Date} [creationDate] The creation date of the formula.
   */
  creationDate?: Date;
  /**
   * @member {LabVirtualMachine} [formulaContent] The content of the formula.
   */
  formulaContent?: LabVirtualMachine;
  /**
   * @member {FormulaPropertiesFromVm} [vm] Information about a VM from which a
   * formula is to be created.
   */
  vm?: FormulaPropertiesFromVm;
  /**
   * @member {string} [provisioningState] The provisioning status of the
   * resource.
   */
  provisioningState?: string;
  /**
   * @member {string} [id] The identifier of the resource.
   */
  id?: string;
  /**
   * @member {string} [name] The name of the resource.
   */
  name?: string;
  /**
   * @member {string} [type] The type of the resource.
   */
  type?: string;
  /**
   * @member {string} [location] The location of the resource.
   */
  location?: string;
  /**
   * @member {{ [propertyName: string]: string }} [tags] The tags of the
   * resource.
   */
  tags?: { [propertyName: string]: string };
}

/**
 * @interface
 * An interface representing GalleryImage.
 * A gallery image.
 *
 * @extends BaseResource
 */
export interface GalleryImage extends BaseResource {
  /**
   * @member {string} [author] The author of the gallery image.
   */
  author?: string;
  /**
   * @member {Date} [createdDate] The creation date of the gallery image.
   */
  createdDate?: Date;
  /**
   * @member {string} [description] The description of the gallery image.
   */
  description?: string;
  /**
   * @member {GalleryImageReference} [imageReference] The image reference of
   * the gallery image.
   */
  imageReference?: GalleryImageReference;
  /**
   * @member {string} [icon] The icon of the gallery image.
   */
  icon?: string;
  /**
   * @member {boolean} [enabled] Indicates whether this gallery image is
   * enabled.
   */
  enabled?: boolean;
  /**
   * @member {string} [id] The identifier of the resource.
   */
  id?: string;
  /**
   * @member {string} [name] The name of the resource.
   */
  name?: string;
  /**
   * @member {string} [type] The type of the resource.
   */
  type?: string;
  /**
   * @member {string} [location] The location of the resource.
   */
  location?: string;
  /**
   * @member {{ [propertyName: string]: string }} [tags] The tags of the
   * resource.
   */
  tags?: { [propertyName: string]: string };
}

/**
 * @interface
 * An interface representing ParameterInfo.
 */
export interface ParameterInfo {
  /**
   * @member {string} [name]
   */
  name?: string;
  /**
   * @member {string} [value]
   */
  value?: string;
}

/**
 * @interface
 * An interface representing GenerateArmTemplateRequest.
 * Parameters for generating an ARM template for deploying artifacts.
 *
 */
export interface GenerateArmTemplateRequest {
  /**
   * @member {string} [virtualMachineName] The resource name of the virtual
   * machine.
   */
  virtualMachineName?: string;
  /**
   * @member {ParameterInfo[]} [parameters] The parameters of the ARM template.
   */
  parameters?: ParameterInfo[];
  /**
   * @member {string} [location] The location of the virtual machine.
   */
  location?: string;
}

/**
 * @interface
 * An interface representing GenerateUploadUriParameter.
 * Properties for generating an upload URI.
 *
 */
export interface GenerateUploadUriParameter {
  /**
   * @member {string} [blobName] The blob name of the upload URI.
   */
  blobName?: string;
}

/**
 * @interface
 * An interface representing GenerateUploadUriResponse.
 * Reponse body for generating an upload URI.
 *
 */
export interface GenerateUploadUriResponse {
  /**
   * @member {string} [uploadUri] The upload URI for the VHD.
   */
  uploadUri?: string;
}

/**
 * @interface
 * An interface representing HourDetails.
 * Properties of an hourly schedule.
 *
 */
export interface HourDetails {
  /**
   * @member {number} [minute] Minutes of the hour the schedule will run.
   */
  minute?: number;
}

/**
 * @interface
 * An interface representing Lab.
 * A lab.
 *
 * @extends BaseResource
 */
export interface Lab extends BaseResource {
  /**
   * @member {string} [defaultStorageAccount] The lab's default storage
   * account.
   */
  defaultStorageAccount?: string;
  /**
   * @member {string} [artifactsStorageAccount] The artifact storage account of
   * the lab.
   */
  artifactsStorageAccount?: string;
  /**
   * @member {string[]} [storageAccounts] The storage accounts of the lab.
   */
  storageAccounts?: string[];
  /**
   * @member {string} [vaultName] The name of the key vault of the lab.
   */
  vaultName?: string;
  /**
   * @member {LabStorageType} [labStorageType] The type of the lab storage.
   * Possible values include: 'Standard', 'Premium'
   */
  labStorageType?: LabStorageType;
  /**
   * @member {string} [defaultVirtualNetworkId] The default virtual network
   * identifier of the lab.
   */
  defaultVirtualNetworkId?: string;
  /**
   * @member {Date} [createdDate] The creation date of the lab.
   */
  createdDate?: Date;
  /**
   * @member {string} [provisioningState] The provisioning status of the
   * resource.
   */
  provisioningState?: string;
  /**
   * @member {string} [id] The identifier of the resource.
   */
  id?: string;
  /**
   * @member {string} [name] The name of the resource.
   */
  name?: string;
  /**
   * @member {string} [type] The type of the resource.
   */
  type?: string;
  /**
   * @member {string} [location] The location of the resource.
   */
  location?: string;
  /**
   * @member {{ [propertyName: string]: string }} [tags] The tags of the
   * resource.
   */
  tags?: { [propertyName: string]: string };
}

/**
 * @interface
 * An interface representing LabVhd.
 * Properties of a VHD in the lab.
 *
 */
export interface LabVhd {
  /**
   * @member {string} [id] The absolute URI of the VHD.
   */
  id?: string;
}

/**
 * @interface
 * An interface representing Policy.
 * A Policy.
 *
 * @extends BaseResource
 */
export interface Policy extends BaseResource {
  /**
   * @member {string} [description] The description of the policy.
   */
  description?: string;
  /**
   * @member {PolicyStatus} [status] The status of the policy. Possible values
   * include: 'Enabled', 'Disabled'
   */
  status?: PolicyStatus;
  /**
   * @member {PolicyFactName} [factName] The fact name of the policy. Possible
   * values include: 'UserOwnedLabVmCount', 'LabVmCount', 'LabVmSize',
   * 'GalleryImage', 'UserOwnedLabVmCountInSubnet'
   */
  factName?: PolicyFactName;
  /**
   * @member {string} [factData] The fact data of the policy.
   */
  factData?: string;
  /**
   * @member {string} [threshold] The threshold of the policy.
   */
  threshold?: string;
  /**
   * @member {PolicyEvaluatorType} [evaluatorType] The evaluator type of the
   * policy. Possible values include: 'AllowedValuesPolicy', 'MaxValuePolicy'
   */
  evaluatorType?: PolicyEvaluatorType;
  /**
   * @member {string} [provisioningState] The provisioning status of the
   * resource.
   */
  provisioningState?: string;
  /**
   * @member {string} [id] The identifier of the resource.
   */
  id?: string;
  /**
   * @member {string} [name] The name of the resource.
   */
  name?: string;
  /**
   * @member {string} [type] The type of the resource.
   */
  type?: string;
  /**
   * @member {string} [location] The location of the resource.
   */
  location?: string;
  /**
   * @member {{ [propertyName: string]: string }} [tags] The tags of the
   * resource.
   */
  tags?: { [propertyName: string]: string };
}

/**
 * @interface
 * An interface representing WeekDetails.
 * Properties of a weekly schedule.
 *
 */
export interface WeekDetails {
  /**
   * @member {string[]} [weekdays] The days of the week.
   */
  weekdays?: string[];
  /**
   * @member {string} [time] The time of the day.
   */
  time?: string;
}

/**
 * @interface
 * An interface representing Schedule.
 * A schedule.
 *
 * @extends BaseResource
 */
export interface Schedule extends BaseResource {
  /**
   * @member {EnableStatus} [status] The status of the schedule. Possible
   * values include: 'Enabled', 'Disabled'
   */
  status?: EnableStatus;
  /**
   * @member {TaskType} [taskType] The task type of the schedule. Possible
   * values include: 'LabVmsShutdownTask', 'LabVmsStartupTask',
   * 'LabBillingTask'
   */
  taskType?: TaskType;
  /**
   * @member {WeekDetails} [weeklyRecurrence] The weekly recurrence of the
   * schedule.
   */
  weeklyRecurrence?: WeekDetails;
  /**
   * @member {DayDetails} [dailyRecurrence] The daily recurrence of the
   * schedule.
   */
  dailyRecurrence?: DayDetails;
  /**
   * @member {HourDetails} [hourlyRecurrence] The hourly recurrence of the
   * schedule.
   */
  hourlyRecurrence?: HourDetails;
  /**
   * @member {string} [timeZoneId] The time zone id.
   */
  timeZoneId?: string;
  /**
   * @member {string} [provisioningState] The provisioning status of the
   * resource.
   */
  provisioningState?: string;
  /**
   * @member {string} [id] The identifier of the resource.
   */
  id?: string;
  /**
   * @member {string} [name] The name of the resource.
   */
  name?: string;
  /**
   * @member {string} [type] The type of the resource.
   */
  type?: string;
  /**
   * @member {string} [location] The location of the resource.
   */
  location?: string;
  /**
   * @member {{ [propertyName: string]: string }} [tags] The tags of the
   * resource.
   */
  tags?: { [propertyName: string]: string };
}

/**
 * @interface
 * An interface representing Subnet.
 */
export interface Subnet {
  /**
   * @member {string} [resourceId]
   */
  resourceId?: string;
  /**
   * @member {string} [labSubnetName]
   */
  labSubnetName?: string;
  /**
   * @member {UsagePermissionType} [allowPublicIp] Possible values include:
   * 'Default', 'Deny', 'Allow'
   */
  allowPublicIp?: UsagePermissionType;
}

/**
 * @interface
 * An interface representing SubnetOverride.
 * Property overrides on a subnet of a virtual network.
 *
 */
export interface SubnetOverride {
  /**
   * @member {string} [resourceId] The resource identifier of the subnet.
   */
  resourceId?: string;
  /**
   * @member {string} [labSubnetName] The name given to the subnet within the
   * lab.
   */
  labSubnetName?: string;
  /**
   * @member {UsagePermissionType} [useInVmCreationPermission] Indicates
   * whether this subnet can be used during virtual machine creation. Possible
   * values include: 'Default', 'Deny', 'Allow'
   */
  useInVmCreationPermission?: UsagePermissionType;
  /**
   * @member {UsagePermissionType} [usePublicIpAddressPermission] Indicates
   * whether public IP addresses can be assigned to virtual machines on this
   * subnet. Possible values include: 'Default', 'Deny', 'Allow'
   */
  usePublicIpAddressPermission?: UsagePermissionType;
}

/**
 * @interface
 * An interface representing SubscriptionNotificationProperties.
 */
export interface SubscriptionNotificationProperties {
  /**
   * @member {string} [tenantId]
   */
  tenantId?: string;
}

/**
 * @interface
 * An interface representing SubscriptionNotification.
 */
export interface SubscriptionNotification {
  /**
   * @member {string} [registrationDate]
   */
  registrationDate?: string;
  /**
   * @member {SubscriptionNotificationState} [state] Possible values include:
   * 'NotDefined', 'Registered', 'Unregistered', 'Warned', 'Suspended',
   * 'Deleted'
   */
  state?: SubscriptionNotificationState;
  /**
   * @member {SubscriptionNotificationProperties} [properties]
   */
  properties?: SubscriptionNotificationProperties;
}

/**
 * @interface
 * An interface representing VirtualNetwork.
 * A virtual network.
 *
 * @extends BaseResource
 */
export interface VirtualNetwork extends BaseResource {
  /**
   * @member {Subnet[]} [allowedSubnets] The allowed subnets of the virtual
   * network.
   */
  allowedSubnets?: Subnet[];
  /**
   * @member {string} [description] The description of the virtual network.
   */
  description?: string;
  /**
   * @member {string} [externalProviderResourceId] The Microsoft.Network
   * resource identifier of the virtual network.
   */
  externalProviderResourceId?: string;
  /**
   * @member {SubnetOverride[]} [subnetOverrides] The subnet overrides of the
   * virtual network.
   */
  subnetOverrides?: SubnetOverride[];
  /**
   * @member {string} [provisioningState] The provisioning status of the
   * resource.
   */
  provisioningState?: string;
  /**
   * @member {string} [id] The identifier of the resource.
   */
  id?: string;
  /**
   * @member {string} [name] The name of the resource.
   */
  name?: string;
  /**
   * @member {string} [type] The type of the resource.
   */
  type?: string;
  /**
   * @member {string} [location] The location of the resource.
   */
  location?: string;
  /**
   * @member {{ [propertyName: string]: string }} [tags] The tags of the
   * resource.
   */
  tags?: { [propertyName: string]: string };
}

/**
 * @interface
 * An interface representing LabListBySubscriptionOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface LabListBySubscriptionOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {string} [filter] The filter to apply on the operation.
   */
  filter?: string;
  /**
   * @member {number} [top]
   */
  top?: number;
  /**
   * @member {string} [orderBy]
   */
  orderBy?: string;
}

/**
 * @interface
 * An interface representing LabListByResourceGroupOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface LabListByResourceGroupOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {string} [filter] The filter to apply on the operation.
   */
  filter?: string;
  /**
   * @member {number} [top]
   */
  top?: number;
  /**
   * @member {string} [orderBy]
   */
  orderBy?: string;
}

/**
 * @interface
 * An interface representing ArtifactSourceListOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface ArtifactSourceListOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {string} [filter] The filter to apply on the operation.
   */
  filter?: string;
  /**
   * @member {number} [top]
   */
  top?: number;
  /**
   * @member {string} [orderBy]
   */
  orderBy?: string;
}

/**
 * @interface
 * An interface representing ArtifactListOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface ArtifactListOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {string} [filter] The filter to apply on the operation.
   */
  filter?: string;
  /**
   * @member {number} [top]
   */
  top?: number;
  /**
   * @member {string} [orderBy]
   */
  orderBy?: string;
}

/**
 * @interface
 * An interface representing CostInsightListOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface CostInsightListOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {string} [filter] The filter to apply on the operation.
   */
  filter?: string;
  /**
   * @member {number} [top]
   */
  top?: number;
  /**
   * @member {string} [orderBy]
   */
  orderBy?: string;
}

/**
 * @interface
 * An interface representing CostListOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface CostListOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {string} [filter] The filter to apply on the operation.
   */
  filter?: string;
  /**
   * @member {number} [top]
   */
  top?: number;
  /**
   * @member {string} [orderBy]
   */
  orderBy?: string;
}

/**
 * @interface
 * An interface representing CustomImageListOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface CustomImageListOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {string} [filter] The filter to apply on the operation.
   */
  filter?: string;
  /**
   * @member {number} [top]
   */
  top?: number;
  /**
   * @member {string} [orderBy]
   */
  orderBy?: string;
}

/**
 * @interface
 * An interface representing FormulaListOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface FormulaListOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {string} [filter] The filter to apply on the operation.
   */
  filter?: string;
  /**
   * @member {number} [top]
   */
  top?: number;
  /**
   * @member {string} [orderBy]
   */
  orderBy?: string;
}

/**
 * @interface
 * An interface representing GalleryImageListOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface GalleryImageListOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {string} [filter] The filter to apply on the operation.
   */
  filter?: string;
  /**
   * @member {number} [top]
   */
  top?: number;
  /**
   * @member {string} [orderBy]
   */
  orderBy?: string;
}

/**
 * @interface
 * An interface representing PolicyListOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface PolicyListOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {string} [filter] The filter to apply on the operation.
   */
  filter?: string;
  /**
   * @member {number} [top]
   */
  top?: number;
  /**
   * @member {string} [orderBy]
   */
  orderBy?: string;
}

/**
 * @interface
 * An interface representing ScheduleListOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface ScheduleListOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {string} [filter] The filter to apply on the operation.
   */
  filter?: string;
  /**
   * @member {number} [top]
   */
  top?: number;
  /**
   * @member {string} [orderBy]
   */
  orderBy?: string;
}

/**
 * @interface
 * An interface representing VirtualMachineListOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface VirtualMachineListOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {string} [filter] The filter to apply on the operation.
   */
  filter?: string;
  /**
   * @member {number} [top]
   */
  top?: number;
  /**
   * @member {string} [orderBy]
   */
  orderBy?: string;
}

/**
 * @interface
 * An interface representing VirtualNetworkListOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface VirtualNetworkListOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {string} [filter] The filter to apply on the operation.
   */
  filter?: string;
  /**
   * @member {number} [top]
   */
  top?: number;
  /**
   * @member {string} [orderBy]
   */
  orderBy?: string;
}

/**
 * @interface
 * An interface representing DevTestLabsClientOptions.
 * @extends AzureServiceClientOptions
 */
export interface DevTestLabsClientOptions extends AzureServiceClientOptions {
  /**
   * @member {string} [baseUri]
   */
  baseUri?: string;
}


/**
 * @interface
 * An interface representing the ResponseWithContinuationLab.
 * The response of a list operation.
 *
 * @extends Array<Lab>
 */
export interface ResponseWithContinuationLab extends Array<Lab> {
  /**
   * @member {string} [nextLink] Link for next set of results.
   */
  nextLink?: string;
}

/**
 * @interface
 * An interface representing the ResponseWithContinuationLabVhd.
 * The response of a list operation.
 *
 * @extends Array<LabVhd>
 */
export interface ResponseWithContinuationLabVhd extends Array<LabVhd> {
  /**
   * @member {string} [nextLink] Link for next set of results.
   */
  nextLink?: string;
}

/**
 * @interface
 * An interface representing the ResponseWithContinuationArtifactSource.
 * The response of a list operation.
 *
 * @extends Array<ArtifactSource>
 */
export interface ResponseWithContinuationArtifactSource extends Array<ArtifactSource> {
  /**
   * @member {string} [nextLink] Link for next set of results.
   */
  nextLink?: string;
}

/**
 * @interface
 * An interface representing the ResponseWithContinuationArtifact.
 * The response of a list operation.
 *
 * @extends Array<Artifact>
 */
export interface ResponseWithContinuationArtifact extends Array<Artifact> {
  /**
   * @member {string} [nextLink] Link for next set of results.
   */
  nextLink?: string;
}

/**
 * @interface
 * An interface representing the ResponseWithContinuationCostInsight.
 * The response of a list operation.
 *
 * @extends Array<CostInsight>
 */
export interface ResponseWithContinuationCostInsight extends Array<CostInsight> {
  /**
   * @member {string} [nextLink] Link for next set of results.
   */
  nextLink?: string;
}

/**
 * @interface
 * An interface representing the ResponseWithContinuationCost.
 * The response of a list operation.
 *
 * @extends Array<Cost>
 */
export interface ResponseWithContinuationCost extends Array<Cost> {
  /**
   * @member {string} [nextLink] Link for next set of results.
   */
  nextLink?: string;
}

/**
 * @interface
 * An interface representing the ResponseWithContinuationCustomImage.
 * The response of a list operation.
 *
 * @extends Array<CustomImage>
 */
export interface ResponseWithContinuationCustomImage extends Array<CustomImage> {
  /**
   * @member {string} [nextLink] Link for next set of results.
   */
  nextLink?: string;
}

/**
 * @interface
 * An interface representing the ResponseWithContinuationFormula.
 * The response of a list operation.
 *
 * @extends Array<Formula>
 */
export interface ResponseWithContinuationFormula extends Array<Formula> {
  /**
   * @member {string} [nextLink] Link for next set of results.
   */
  nextLink?: string;
}

/**
 * @interface
 * An interface representing the ResponseWithContinuationGalleryImage.
 * The response of a list operation.
 *
 * @extends Array<GalleryImage>
 */
export interface ResponseWithContinuationGalleryImage extends Array<GalleryImage> {
  /**
   * @member {string} [nextLink] Link for next set of results.
   */
  nextLink?: string;
}

/**
 * @interface
 * An interface representing the ResponseWithContinuationPolicy.
 * The response of a list operation.
 *
 * @extends Array<Policy>
 */
export interface ResponseWithContinuationPolicy extends Array<Policy> {
  /**
   * @member {string} [nextLink] Link for next set of results.
   */
  nextLink?: string;
}

/**
 * @interface
 * An interface representing the ResponseWithContinuationSchedule.
 * The response of a list operation.
 *
 * @extends Array<Schedule>
 */
export interface ResponseWithContinuationSchedule extends Array<Schedule> {
  /**
   * @member {string} [nextLink] Link for next set of results.
   */
  nextLink?: string;
}

/**
 * @interface
 * An interface representing the ResponseWithContinuationLabVirtualMachine.
 * The response of a list operation.
 *
 * @extends Array<LabVirtualMachine>
 */
export interface ResponseWithContinuationLabVirtualMachine extends Array<LabVirtualMachine> {
  /**
   * @member {string} [nextLink] Link for next set of results.
   */
  nextLink?: string;
}

/**
 * @interface
 * An interface representing the ResponseWithContinuationVirtualNetwork.
 * The response of a list operation.
 *
 * @extends Array<VirtualNetwork>
 */
export interface ResponseWithContinuationVirtualNetwork extends Array<VirtualNetwork> {
  /**
   * @member {string} [nextLink] Link for next set of results.
   */
  nextLink?: string;
}

/**
 * Defines values for SourceControlType.
 * Possible values include: 'VsoGit', 'GitHub'
 * There could be more values for this enum apart from the ones defined here.If
 * you want to set a value that is not from the known values then you can do
 * the following:
 * let param: SourceControlType =
 * <SourceControlType>"someUnknownValueThatWillStillBeValid";
 * @readonly
 * @enum {string}
 */
export enum SourceControlType {
  VsoGit = 'VsoGit',
  GitHub = 'GitHub',
}

/**
 * Defines values for EnableStatus.
 * Possible values include: 'Enabled', 'Disabled'
 * There could be more values for this enum apart from the ones defined here.If
 * you want to set a value that is not from the known values then you can do
 * the following:
 * let param: EnableStatus =
 * <EnableStatus>"someUnknownValueThatWillStillBeValid";
 * @readonly
 * @enum {string}
 */
export enum EnableStatus {
  Enabled = 'Enabled',
  Disabled = 'Disabled',
}

/**
 * Defines values for CostPropertyType.
 * Possible values include: 'Unavailable', 'Reported', 'Projected'
 * There could be more values for this enum apart from the ones defined here.If
 * you want to set a value that is not from the known values then you can do
 * the following:
 * let param: CostPropertyType =
 * <CostPropertyType>"someUnknownValueThatWillStillBeValid";
 * @readonly
 * @enum {string}
 */
export enum CostPropertyType {
  Unavailable = 'Unavailable',
  Reported = 'Reported',
  Projected = 'Projected',
}

/**
 * Defines values for WindowsOsState.
 * Possible values include: 'NonSysprepped', 'SysprepRequested',
 * 'SysprepApplied'
 * There could be more values for this enum apart from the ones defined here.If
 * you want to set a value that is not from the known values then you can do
 * the following:
 * let param: WindowsOsState =
 * <WindowsOsState>"someUnknownValueThatWillStillBeValid";
 * @readonly
 * @enum {string}
 */
export enum WindowsOsState {
  NonSysprepped = 'NonSysprepped',
  SysprepRequested = 'SysprepRequested',
  SysprepApplied = 'SysprepApplied',
}

/**
 * Defines values for LinuxOsState.
 * Possible values include: 'NonDeprovisioned', 'DeprovisionRequested',
 * 'DeprovisionApplied'
 * There could be more values for this enum apart from the ones defined here.If
 * you want to set a value that is not from the known values then you can do
 * the following:
 * let param: LinuxOsState =
 * <LinuxOsState>"someUnknownValueThatWillStillBeValid";
 * @readonly
 * @enum {string}
 */
export enum LinuxOsState {
  NonDeprovisioned = 'NonDeprovisioned',
  DeprovisionRequested = 'DeprovisionRequested',
  DeprovisionApplied = 'DeprovisionApplied',
}

/**
 * Defines values for CustomImageOsType.
 * Possible values include: 'Windows', 'Linux', 'None'
 * There could be more values for this enum apart from the ones defined here.If
 * you want to set a value that is not from the known values then you can do
 * the following:
 * let param: CustomImageOsType =
 * <CustomImageOsType>"someUnknownValueThatWillStillBeValid";
 * @readonly
 * @enum {string}
 */
export enum CustomImageOsType {
  Windows = 'Windows',
  Linux = 'Linux',
  None = 'None',
}

/**
 * Defines values for LabStorageType.
 * Possible values include: 'Standard', 'Premium'
 * There could be more values for this enum apart from the ones defined here.If
 * you want to set a value that is not from the known values then you can do
 * the following:
 * let param: LabStorageType =
 * <LabStorageType>"someUnknownValueThatWillStillBeValid";
 * @readonly
 * @enum {string}
 */
export enum LabStorageType {
  Standard = 'Standard',
  Premium = 'Premium',
}

/**
 * Defines values for PolicyStatus.
 * Possible values include: 'Enabled', 'Disabled'
 * There could be more values for this enum apart from the ones defined here.If
 * you want to set a value that is not from the known values then you can do
 * the following:
 * let param: PolicyStatus =
 * <PolicyStatus>"someUnknownValueThatWillStillBeValid";
 * @readonly
 * @enum {string}
 */
export enum PolicyStatus {
  Enabled = 'Enabled',
  Disabled = 'Disabled',
}

/**
 * Defines values for PolicyFactName.
 * Possible values include: 'UserOwnedLabVmCount', 'LabVmCount', 'LabVmSize',
 * 'GalleryImage', 'UserOwnedLabVmCountInSubnet'
 * There could be more values for this enum apart from the ones defined here.If
 * you want to set a value that is not from the known values then you can do
 * the following:
 * let param: PolicyFactName =
 * <PolicyFactName>"someUnknownValueThatWillStillBeValid";
 * @readonly
 * @enum {string}
 */
export enum PolicyFactName {
  UserOwnedLabVmCount = 'UserOwnedLabVmCount',
  LabVmCount = 'LabVmCount',
  LabVmSize = 'LabVmSize',
  GalleryImage = 'GalleryImage',
  UserOwnedLabVmCountInSubnet = 'UserOwnedLabVmCountInSubnet',
}

/**
 * Defines values for PolicyEvaluatorType.
 * Possible values include: 'AllowedValuesPolicy', 'MaxValuePolicy'
 * There could be more values for this enum apart from the ones defined here.If
 * you want to set a value that is not from the known values then you can do
 * the following:
 * let param: PolicyEvaluatorType =
 * <PolicyEvaluatorType>"someUnknownValueThatWillStillBeValid";
 * @readonly
 * @enum {string}
 */
export enum PolicyEvaluatorType {
  AllowedValuesPolicy = 'AllowedValuesPolicy',
  MaxValuePolicy = 'MaxValuePolicy',
}

/**
 * Defines values for TaskType.
 * Possible values include: 'LabVmsShutdownTask', 'LabVmsStartupTask',
 * 'LabBillingTask'
 * There could be more values for this enum apart from the ones defined here.If
 * you want to set a value that is not from the known values then you can do
 * the following:
 * let param: TaskType = <TaskType>"someUnknownValueThatWillStillBeValid";
 * @readonly
 * @enum {string}
 */
export enum TaskType {
  LabVmsShutdownTask = 'LabVmsShutdownTask',
  LabVmsStartupTask = 'LabVmsStartupTask',
  LabBillingTask = 'LabBillingTask',
}

/**
 * Defines values for UsagePermissionType.
 * Possible values include: 'Default', 'Deny', 'Allow'
 * There could be more values for this enum apart from the ones defined here.If
 * you want to set a value that is not from the known values then you can do
 * the following:
 * let param: UsagePermissionType =
 * <UsagePermissionType>"someUnknownValueThatWillStillBeValid";
 * @readonly
 * @enum {string}
 */
export enum UsagePermissionType {
  Default = 'Default',
  Deny = 'Deny',
  Allow = 'Allow',
}

/**
 * Defines values for SubscriptionNotificationState.
 * Possible values include: 'NotDefined', 'Registered', 'Unregistered',
 * 'Warned', 'Suspended', 'Deleted'
 * There could be more values for this enum apart from the ones defined here.If
 * you want to set a value that is not from the known values then you can do
 * the following:
 * let param: SubscriptionNotificationState =
 * <SubscriptionNotificationState>"someUnknownValueThatWillStillBeValid";
 * @readonly
 * @enum {string}
 */
export enum SubscriptionNotificationState {
  NotDefined = 'NotDefined',
  Registered = 'Registered',
  Unregistered = 'Unregistered',
  Warned = 'Warned',
  Suspended = 'Suspended',
  Deleted = 'Deleted',
}

/**
 * Contains response data for the listBySubscription operation.
 */
export type LabListBySubscriptionResponse = ResponseWithContinuationLab & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: ResponseWithContinuationLab;
    };
};

/**
 * Contains response data for the listByResourceGroup operation.
 */
export type LabListByResourceGroupResponse = ResponseWithContinuationLab & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: ResponseWithContinuationLab;
    };
};

/**
 * Contains response data for the getResource operation.
 */
export type LabGetResourceResponse = Lab & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: Lab;
    };
};

/**
 * Contains response data for the createOrUpdateResource operation.
 */
export type LabCreateOrUpdateResourceResponse = Lab & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: Lab;
    };
};

/**
 * Contains response data for the patchResource operation.
 */
export type LabPatchResourceResponse = Lab & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: Lab;
    };
};

/**
 * Contains response data for the generateUploadUri operation.
 */
export type LabGenerateUploadUriResponse = GenerateUploadUriResponse & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: GenerateUploadUriResponse;
    };
};

/**
 * Contains response data for the listVhds operation.
 */
export type LabListVhdsResponse = ResponseWithContinuationLabVhd & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: ResponseWithContinuationLabVhd;
    };
};

/**
 * Contains response data for the beginCreateOrUpdateResource operation.
 */
export type LabBeginCreateOrUpdateResourceResponse = Lab & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: Lab;
    };
};

/**
 * Contains response data for the listBySubscriptionNext operation.
 */
export type LabListBySubscriptionNextResponse = ResponseWithContinuationLab & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: ResponseWithContinuationLab;
    };
};

/**
 * Contains response data for the listByResourceGroupNext operation.
 */
export type LabListByResourceGroupNextResponse = ResponseWithContinuationLab & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: ResponseWithContinuationLab;
    };
};

/**
 * Contains response data for the listVhdsNext operation.
 */
export type LabListVhdsNextResponse = ResponseWithContinuationLabVhd & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: ResponseWithContinuationLabVhd;
    };
};

/**
 * Contains response data for the list operation.
 */
export type ArtifactSourceListResponse = ResponseWithContinuationArtifactSource & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: ResponseWithContinuationArtifactSource;
    };
};

/**
 * Contains response data for the getResource operation.
 */
export type ArtifactSourceGetResourceResponse = ArtifactSource & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: ArtifactSource;
    };
};

/**
 * Contains response data for the createOrUpdateResource operation.
 */
export type ArtifactSourceCreateOrUpdateResourceResponse = ArtifactSource & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: ArtifactSource;
    };
};

/**
 * Contains response data for the patchResource operation.
 */
export type ArtifactSourcePatchResourceResponse = ArtifactSource & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: ArtifactSource;
    };
};

/**
 * Contains response data for the listNext operation.
 */
export type ArtifactSourceListNextResponse = ResponseWithContinuationArtifactSource & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: ResponseWithContinuationArtifactSource;
    };
};

/**
 * Contains response data for the list operation.
 */
export type ArtifactListResponse = ResponseWithContinuationArtifact & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: ResponseWithContinuationArtifact;
    };
};

/**
 * Contains response data for the getResource operation.
 */
export type ArtifactGetResourceResponse = Artifact & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: Artifact;
    };
};

/**
 * Contains response data for the generateArmTemplate operation.
 */
export type ArtifactGenerateArmTemplateResponse = ArmTemplateInfo & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: ArmTemplateInfo;
    };
};

/**
 * Contains response data for the listNext operation.
 */
export type ArtifactListNextResponse = ResponseWithContinuationArtifact & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: ResponseWithContinuationArtifact;
    };
};

/**
 * Contains response data for the list operation.
 */
export type CostInsightListResponse = ResponseWithContinuationCostInsight & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: ResponseWithContinuationCostInsight;
    };
};

/**
 * Contains response data for the getResource operation.
 */
export type CostInsightGetResourceResponse = CostInsight & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: CostInsight;
    };
};

/**
 * Contains response data for the listNext operation.
 */
export type CostInsightListNextResponse = ResponseWithContinuationCostInsight & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: ResponseWithContinuationCostInsight;
    };
};

/**
 * Contains response data for the list operation.
 */
export type CostListResponse = ResponseWithContinuationCost & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: ResponseWithContinuationCost;
    };
};

/**
 * Contains response data for the getResource operation.
 */
export type CostGetResourceResponse = Cost & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: Cost;
    };
};

/**
 * Contains response data for the listNext operation.
 */
export type CostListNextResponse = ResponseWithContinuationCost & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: ResponseWithContinuationCost;
    };
};

/**
 * Contains response data for the list operation.
 */
export type CustomImageListResponse = ResponseWithContinuationCustomImage & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: ResponseWithContinuationCustomImage;
    };
};

/**
 * Contains response data for the getResource operation.
 */
export type CustomImageGetResourceResponse = CustomImage & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: CustomImage;
    };
};

/**
 * Contains response data for the createOrUpdateResource operation.
 */
export type CustomImageCreateOrUpdateResourceResponse = CustomImage & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: CustomImage;
    };
};

/**
 * Contains response data for the beginCreateOrUpdateResource operation.
 */
export type CustomImageBeginCreateOrUpdateResourceResponse = CustomImage & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: CustomImage;
    };
};

/**
 * Contains response data for the listNext operation.
 */
export type CustomImageListNextResponse = ResponseWithContinuationCustomImage & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: ResponseWithContinuationCustomImage;
    };
};

/**
 * Contains response data for the list operation.
 */
export type FormulaListResponse = ResponseWithContinuationFormula & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: ResponseWithContinuationFormula;
    };
};

/**
 * Contains response data for the getResource operation.
 */
export type FormulaGetResourceResponse = Formula & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: Formula;
    };
};

/**
 * Contains response data for the createOrUpdateResource operation.
 */
export type FormulaCreateOrUpdateResourceResponse = Formula & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: Formula;
    };
};

/**
 * Contains response data for the beginCreateOrUpdateResource operation.
 */
export type FormulaBeginCreateOrUpdateResourceResponse = Formula & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: Formula;
    };
};

/**
 * Contains response data for the listNext operation.
 */
export type FormulaListNextResponse = ResponseWithContinuationFormula & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: ResponseWithContinuationFormula;
    };
};

/**
 * Contains response data for the list operation.
 */
export type GalleryImageListResponse = ResponseWithContinuationGalleryImage & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: ResponseWithContinuationGalleryImage;
    };
};

/**
 * Contains response data for the listNext operation.
 */
export type GalleryImageListNextResponse = ResponseWithContinuationGalleryImage & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: ResponseWithContinuationGalleryImage;
    };
};

/**
 * Contains response data for the evaluatePolicies operation.
 */
export type PolicySetEvaluatePoliciesResponse = EvaluatePoliciesResponse & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: EvaluatePoliciesResponse;
    };
};

/**
 * Contains response data for the list operation.
 */
export type PolicyListResponse = ResponseWithContinuationPolicy & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: ResponseWithContinuationPolicy;
    };
};

/**
 * Contains response data for the getResource operation.
 */
export type PolicyGetResourceResponse = Policy & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: Policy;
    };
};

/**
 * Contains response data for the createOrUpdateResource operation.
 */
export type PolicyCreateOrUpdateResourceResponse = Policy & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: Policy;
    };
};

/**
 * Contains response data for the patchResource operation.
 */
export type PolicyPatchResourceResponse = Policy & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: Policy;
    };
};

/**
 * Contains response data for the listNext operation.
 */
export type PolicyListNextResponse = ResponseWithContinuationPolicy & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: ResponseWithContinuationPolicy;
    };
};

/**
 * Contains response data for the list operation.
 */
export type ScheduleListResponse = ResponseWithContinuationSchedule & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: ResponseWithContinuationSchedule;
    };
};

/**
 * Contains response data for the getResource operation.
 */
export type ScheduleGetResourceResponse = Schedule & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: Schedule;
    };
};

/**
 * Contains response data for the createOrUpdateResource operation.
 */
export type ScheduleCreateOrUpdateResourceResponse = Schedule & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: Schedule;
    };
};

/**
 * Contains response data for the patchResource operation.
 */
export type SchedulePatchResourceResponse = Schedule & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: Schedule;
    };
};

/**
 * Contains response data for the beginCreateOrUpdateResource operation.
 */
export type ScheduleBeginCreateOrUpdateResourceResponse = Schedule & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: Schedule;
    };
};

/**
 * Contains response data for the listNext operation.
 */
export type ScheduleListNextResponse = ResponseWithContinuationSchedule & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: ResponseWithContinuationSchedule;
    };
};

/**
 * Contains response data for the list operation.
 */
export type VirtualMachineListResponse = ResponseWithContinuationLabVirtualMachine & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: ResponseWithContinuationLabVirtualMachine;
    };
};

/**
 * Contains response data for the getResource operation.
 */
export type VirtualMachineGetResourceResponse = LabVirtualMachine & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: LabVirtualMachine;
    };
};

/**
 * Contains response data for the createOrUpdateResource operation.
 */
export type VirtualMachineCreateOrUpdateResourceResponse = LabVirtualMachine & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: LabVirtualMachine;
    };
};

/**
 * Contains response data for the patchResource operation.
 */
export type VirtualMachinePatchResourceResponse = LabVirtualMachine & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: LabVirtualMachine;
    };
};

/**
 * Contains response data for the beginCreateOrUpdateResource operation.
 */
export type VirtualMachineBeginCreateOrUpdateResourceResponse = LabVirtualMachine & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: LabVirtualMachine;
    };
};

/**
 * Contains response data for the listNext operation.
 */
export type VirtualMachineListNextResponse = ResponseWithContinuationLabVirtualMachine & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: ResponseWithContinuationLabVirtualMachine;
    };
};

/**
 * Contains response data for the list operation.
 */
export type VirtualNetworkListResponse = ResponseWithContinuationVirtualNetwork & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: ResponseWithContinuationVirtualNetwork;
    };
};

/**
 * Contains response data for the getResource operation.
 */
export type VirtualNetworkGetResourceResponse = VirtualNetwork & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: VirtualNetwork;
    };
};

/**
 * Contains response data for the createOrUpdateResource operation.
 */
export type VirtualNetworkCreateOrUpdateResourceResponse = VirtualNetwork & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: VirtualNetwork;
    };
};

/**
 * Contains response data for the patchResource operation.
 */
export type VirtualNetworkPatchResourceResponse = VirtualNetwork & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: VirtualNetwork;
    };
};

/**
 * Contains response data for the beginCreateOrUpdateResource operation.
 */
export type VirtualNetworkBeginCreateOrUpdateResourceResponse = VirtualNetwork & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: VirtualNetwork;
    };
};

/**
 * Contains response data for the listNext operation.
 */
export type VirtualNetworkListNextResponse = ResponseWithContinuationVirtualNetwork & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: ResponseWithContinuationVirtualNetwork;
    };
};
