/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import { CloudErrorMapper, BaseResourceMapper } from "ms-rest-azure-js";
import * as msRest from "ms-rest-js";

export const CloudError = CloudErrorMapper;
export const BaseResource = BaseResourceMapper;

export const ArtifactParameterProperties: msRest.CompositeMapper = {
  serializedName: "ArtifactParameterProperties",
  type: {
    name: "Composite",
    className: "ArtifactParameterProperties",
    modelProperties: {
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      value: {
        serializedName: "value",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const ArtifactInstallProperties: msRest.CompositeMapper = {
  serializedName: "ArtifactInstallProperties",
  type: {
    name: "Composite",
    className: "ArtifactInstallProperties",
    modelProperties: {
      artifactId: {
        serializedName: "artifactId",
        type: {
          name: "String"
        }
      },
      parameters: {
        serializedName: "parameters",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "ArtifactParameterProperties"
            }
          }
        }
      }
    }
  }
};

export const ApplyArtifactsRequest: msRest.CompositeMapper = {
  serializedName: "ApplyArtifactsRequest",
  type: {
    name: "Composite",
    className: "ApplyArtifactsRequest",
    modelProperties: {
      artifacts: {
        serializedName: "artifacts",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "ArtifactInstallProperties"
            }
          }
        }
      }
    }
  }
};

export const ArmTemplateInfo: msRest.CompositeMapper = {
  serializedName: "ArmTemplateInfo",
  type: {
    name: "Composite",
    className: "ArmTemplateInfo",
    modelProperties: {
      template: {
        serializedName: "template",
        type: {
          name: "Object"
        }
      },
      parameters: {
        serializedName: "parameters",
        type: {
          name: "Object"
        }
      }
    }
  }
};

export const Artifact: msRest.CompositeMapper = {
  serializedName: "Artifact",
  type: {
    name: "Composite",
    className: "Artifact",
    modelProperties: {
      title: {
        serializedName: "properties.title",
        type: {
          name: "String"
        }
      },
      description: {
        serializedName: "properties.description",
        type: {
          name: "String"
        }
      },
      filePath: {
        serializedName: "properties.filePath",
        type: {
          name: "String"
        }
      },
      icon: {
        serializedName: "properties.icon",
        type: {
          name: "String"
        }
      },
      targetOsType: {
        serializedName: "properties.targetOsType",
        type: {
          name: "String"
        }
      },
      parameters: {
        serializedName: "properties.parameters",
        type: {
          name: "Object"
        }
      },
      id: {
        serializedName: "id",
        type: {
          name: "String"
        }
      },
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      type: {
        serializedName: "type",
        type: {
          name: "String"
        }
      },
      location: {
        serializedName: "location",
        type: {
          name: "String"
        }
      },
      tags: {
        serializedName: "tags",
        type: {
          name: "Dictionary",
          value: {
            type: {
              name: "String"
            }
          }
        }
      }
    }
  }
};

export const ArtifactDeploymentStatusProperties: msRest.CompositeMapper = {
  serializedName: "ArtifactDeploymentStatusProperties",
  type: {
    name: "Composite",
    className: "ArtifactDeploymentStatusProperties",
    modelProperties: {
      deploymentStatus: {
        serializedName: "deploymentStatus",
        type: {
          name: "String"
        }
      },
      artifactsApplied: {
        serializedName: "artifactsApplied",
        type: {
          name: "Number"
        }
      },
      totalArtifacts: {
        serializedName: "totalArtifacts",
        type: {
          name: "Number"
        }
      }
    }
  }
};

export const ArtifactSource: msRest.CompositeMapper = {
  serializedName: "ArtifactSource",
  type: {
    name: "Composite",
    className: "ArtifactSource",
    modelProperties: {
      displayName: {
        serializedName: "properties.displayName",
        type: {
          name: "String"
        }
      },
      uri: {
        serializedName: "properties.uri",
        type: {
          name: "String"
        }
      },
      sourceType: {
        serializedName: "properties.sourceType",
        type: {
          name: "String"
        }
      },
      folderPath: {
        serializedName: "properties.folderPath",
        type: {
          name: "String"
        }
      },
      branchRef: {
        serializedName: "properties.branchRef",
        type: {
          name: "String"
        }
      },
      securityToken: {
        serializedName: "properties.securityToken",
        type: {
          name: "String"
        }
      },
      status: {
        serializedName: "properties.status",
        type: {
          name: "String"
        }
      },
      provisioningState: {
        serializedName: "properties.provisioningState",
        type: {
          name: "String"
        }
      },
      id: {
        serializedName: "id",
        type: {
          name: "String"
        }
      },
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      type: {
        serializedName: "type",
        type: {
          name: "String"
        }
      },
      location: {
        serializedName: "location",
        type: {
          name: "String"
        }
      },
      tags: {
        serializedName: "tags",
        type: {
          name: "Dictionary",
          value: {
            type: {
              name: "String"
            }
          }
        }
      }
    }
  }
};

export const CostPerDayProperties: msRest.CompositeMapper = {
  serializedName: "CostPerDayProperties",
  type: {
    name: "Composite",
    className: "CostPerDayProperties",
    modelProperties: {
      date: {
        serializedName: "date",
        type: {
          name: "DateTime"
        }
      },
      cost: {
        serializedName: "cost",
        type: {
          name: "Number"
        }
      },
      costType: {
        serializedName: "costType",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const Cost: msRest.CompositeMapper = {
  serializedName: "Cost",
  type: {
    name: "Composite",
    className: "Cost",
    modelProperties: {
      currencyCode: {
        serializedName: "properties.currencyCode",
        type: {
          name: "String"
        }
      },
      costs: {
        serializedName: "properties.costs",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "CostPerDayProperties"
            }
          }
        }
      },
      id: {
        serializedName: "id",
        type: {
          name: "String"
        }
      },
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      type: {
        serializedName: "type",
        type: {
          name: "String"
        }
      },
      location: {
        serializedName: "location",
        type: {
          name: "String"
        }
      },
      tags: {
        serializedName: "tags",
        type: {
          name: "Dictionary",
          value: {
            type: {
              name: "String"
            }
          }
        }
      }
    }
  }
};

export const VMCostProperties: msRest.CompositeMapper = {
  serializedName: "VMCostProperties",
  type: {
    name: "Composite",
    className: "VMCostProperties",
    modelProperties: {
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      resourceGroupName: {
        serializedName: "resourceGroupName",
        type: {
          name: "String"
        }
      },
      cost: {
        serializedName: "cost",
        type: {
          name: "Number"
        }
      }
    }
  }
};

export const CostInsight: msRest.CompositeMapper = {
  serializedName: "CostInsight",
  type: {
    name: "Composite",
    className: "CostInsight",
    modelProperties: {
      currencyCode: {
        serializedName: "properties.currencyCode",
        type: {
          name: "String"
        }
      },
      vmCosts: {
        serializedName: "properties.vmCosts",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "VMCostProperties"
            }
          }
        }
      },
      provisioningState: {
        serializedName: "properties.provisioningState",
        type: {
          name: "String"
        }
      },
      id: {
        serializedName: "id",
        type: {
          name: "String"
        }
      },
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      type: {
        serializedName: "type",
        type: {
          name: "String"
        }
      },
      location: {
        serializedName: "location",
        type: {
          name: "String"
        }
      },
      tags: {
        serializedName: "tags",
        type: {
          name: "Dictionary",
          value: {
            type: {
              name: "String"
            }
          }
        }
      }
    }
  }
};

export const WindowsOsInfo: msRest.CompositeMapper = {
  serializedName: "WindowsOsInfo",
  type: {
    name: "Composite",
    className: "WindowsOsInfo",
    modelProperties: {
      windowsOsState: {
        serializedName: "windowsOsState",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const LinuxOsInfo: msRest.CompositeMapper = {
  serializedName: "LinuxOsInfo",
  type: {
    name: "Composite",
    className: "LinuxOsInfo",
    modelProperties: {
      linuxOsState: {
        serializedName: "linuxOsState",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const CustomImagePropertiesFromVm: msRest.CompositeMapper = {
  serializedName: "CustomImagePropertiesFromVm",
  type: {
    name: "Composite",
    className: "CustomImagePropertiesFromVm",
    modelProperties: {
      sourceVmId: {
        serializedName: "sourceVmId",
        type: {
          name: "String"
        }
      },
      sysPrep: {
        serializedName: "sysPrep",
        type: {
          name: "Boolean"
        }
      },
      windowsOsInfo: {
        serializedName: "windowsOsInfo",
        type: {
          name: "Composite",
          className: "WindowsOsInfo"
        }
      },
      linuxOsInfo: {
        serializedName: "linuxOsInfo",
        type: {
          name: "Composite",
          className: "LinuxOsInfo"
        }
      }
    }
  }
};

export const CustomImagePropertiesCustom: msRest.CompositeMapper = {
  serializedName: "CustomImagePropertiesCustom",
  type: {
    name: "Composite",
    className: "CustomImagePropertiesCustom",
    modelProperties: {
      imageName: {
        serializedName: "imageName",
        type: {
          name: "String"
        }
      },
      sysPrep: {
        serializedName: "sysPrep",
        type: {
          name: "Boolean"
        }
      }
    }
  }
};

export const CustomImage: msRest.CompositeMapper = {
  serializedName: "CustomImage",
  type: {
    name: "Composite",
    className: "CustomImage",
    modelProperties: {
      vm: {
        serializedName: "properties.vm",
        type: {
          name: "Composite",
          className: "CustomImagePropertiesFromVm"
        }
      },
      vhd: {
        serializedName: "properties.vhd",
        type: {
          name: "Composite",
          className: "CustomImagePropertiesCustom"
        }
      },
      description: {
        serializedName: "properties.description",
        type: {
          name: "String"
        }
      },
      osType: {
        serializedName: "properties.osType",
        type: {
          name: "String"
        }
      },
      author: {
        serializedName: "properties.author",
        type: {
          name: "String"
        }
      },
      creationDate: {
        serializedName: "properties.creationDate",
        type: {
          name: "DateTime"
        }
      },
      provisioningState: {
        serializedName: "properties.provisioningState",
        type: {
          name: "String"
        }
      },
      id: {
        serializedName: "id",
        type: {
          name: "String"
        }
      },
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      type: {
        serializedName: "type",
        type: {
          name: "String"
        }
      },
      location: {
        serializedName: "location",
        type: {
          name: "String"
        }
      },
      tags: {
        serializedName: "tags",
        type: {
          name: "Dictionary",
          value: {
            type: {
              name: "String"
            }
          }
        }
      }
    }
  }
};

export const DayDetails: msRest.CompositeMapper = {
  serializedName: "DayDetails",
  type: {
    name: "Composite",
    className: "DayDetails",
    modelProperties: {
      time: {
        serializedName: "time",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const EvaluatePoliciesProperties: msRest.CompositeMapper = {
  serializedName: "EvaluatePoliciesProperties",
  type: {
    name: "Composite",
    className: "EvaluatePoliciesProperties",
    modelProperties: {
      factName: {
        serializedName: "factName",
        type: {
          name: "String"
        }
      },
      factData: {
        serializedName: "factData",
        type: {
          name: "String"
        }
      },
      valueOffset: {
        serializedName: "valueOffset",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const EvaluatePoliciesRequest: msRest.CompositeMapper = {
  serializedName: "EvaluatePoliciesRequest",
  type: {
    name: "Composite",
    className: "EvaluatePoliciesRequest",
    modelProperties: {
      policies: {
        serializedName: "policies",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "EvaluatePoliciesProperties"
            }
          }
        }
      }
    }
  }
};

export const PolicyViolation: msRest.CompositeMapper = {
  serializedName: "PolicyViolation",
  type: {
    name: "Composite",
    className: "PolicyViolation",
    modelProperties: {
      code: {
        serializedName: "code",
        type: {
          name: "String"
        }
      },
      message: {
        serializedName: "message",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const PolicySetResult: msRest.CompositeMapper = {
  serializedName: "PolicySetResult",
  type: {
    name: "Composite",
    className: "PolicySetResult",
    modelProperties: {
      hasError: {
        serializedName: "hasError",
        type: {
          name: "Boolean"
        }
      },
      policyViolations: {
        serializedName: "policyViolations",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "PolicyViolation"
            }
          }
        }
      }
    }
  }
};

export const EvaluatePoliciesResponse: msRest.CompositeMapper = {
  serializedName: "EvaluatePoliciesResponse",
  type: {
    name: "Composite",
    className: "EvaluatePoliciesResponse",
    modelProperties: {
      results: {
        serializedName: "results",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "PolicySetResult"
            }
          }
        }
      }
    }
  }
};

export const GalleryImageReference: msRest.CompositeMapper = {
  serializedName: "GalleryImageReference",
  type: {
    name: "Composite",
    className: "GalleryImageReference",
    modelProperties: {
      offer: {
        serializedName: "offer",
        type: {
          name: "String"
        }
      },
      publisher: {
        serializedName: "publisher",
        type: {
          name: "String"
        }
      },
      sku: {
        serializedName: "sku",
        type: {
          name: "String"
        }
      },
      osType: {
        serializedName: "osType",
        type: {
          name: "String"
        }
      },
      version: {
        serializedName: "version",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const LabVirtualMachine: msRest.CompositeMapper = {
  serializedName: "LabVirtualMachine",
  type: {
    name: "Composite",
    className: "LabVirtualMachine",
    modelProperties: {
      notes: {
        serializedName: "properties.notes",
        type: {
          name: "String"
        }
      },
      ownerObjectId: {
        serializedName: "properties.ownerObjectId",
        type: {
          name: "String"
        }
      },
      createdByUserId: {
        serializedName: "properties.createdByUserId",
        type: {
          name: "String"
        }
      },
      createdByUser: {
        serializedName: "properties.createdByUser",
        type: {
          name: "String"
        }
      },
      computeId: {
        serializedName: "properties.computeId",
        type: {
          name: "String"
        }
      },
      customImageId: {
        serializedName: "properties.customImageId",
        type: {
          name: "String"
        }
      },
      osType: {
        serializedName: "properties.osType",
        type: {
          name: "String"
        }
      },
      size: {
        serializedName: "properties.size",
        type: {
          name: "String"
        }
      },
      userName: {
        serializedName: "properties.userName",
        type: {
          name: "String"
        }
      },
      password: {
        serializedName: "properties.password",
        type: {
          name: "String"
        }
      },
      sshKey: {
        serializedName: "properties.sshKey",
        type: {
          name: "String"
        }
      },
      isAuthenticationWithSshKey: {
        serializedName: "properties.isAuthenticationWithSshKey",
        type: {
          name: "Boolean"
        }
      },
      fqdn: {
        serializedName: "properties.fqdn",
        type: {
          name: "String"
        }
      },
      labSubnetName: {
        serializedName: "properties.labSubnetName",
        type: {
          name: "String"
        }
      },
      labVirtualNetworkId: {
        serializedName: "properties.labVirtualNetworkId",
        type: {
          name: "String"
        }
      },
      disallowPublicIpAddress: {
        serializedName: "properties.disallowPublicIpAddress",
        type: {
          name: "Boolean"
        }
      },
      artifacts: {
        serializedName: "properties.artifacts",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "ArtifactInstallProperties"
            }
          }
        }
      },
      artifactDeploymentStatus: {
        serializedName: "properties.artifactDeploymentStatus",
        type: {
          name: "Composite",
          className: "ArtifactDeploymentStatusProperties"
        }
      },
      galleryImageReference: {
        serializedName: "properties.galleryImageReference",
        type: {
          name: "Composite",
          className: "GalleryImageReference"
        }
      },
      provisioningState: {
        serializedName: "properties.provisioningState",
        type: {
          name: "String"
        }
      },
      id: {
        serializedName: "id",
        type: {
          name: "String"
        }
      },
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      type: {
        serializedName: "type",
        type: {
          name: "String"
        }
      },
      location: {
        serializedName: "location",
        type: {
          name: "String"
        }
      },
      tags: {
        serializedName: "tags",
        type: {
          name: "Dictionary",
          value: {
            type: {
              name: "String"
            }
          }
        }
      }
    }
  }
};

export const FormulaPropertiesFromVm: msRest.CompositeMapper = {
  serializedName: "FormulaPropertiesFromVm",
  type: {
    name: "Composite",
    className: "FormulaPropertiesFromVm",
    modelProperties: {
      labVmId: {
        serializedName: "labVmId",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const Formula: msRest.CompositeMapper = {
  serializedName: "Formula",
  type: {
    name: "Composite",
    className: "Formula",
    modelProperties: {
      description: {
        serializedName: "properties.description",
        type: {
          name: "String"
        }
      },
      author: {
        serializedName: "properties.author",
        type: {
          name: "String"
        }
      },
      osType: {
        serializedName: "properties.osType",
        type: {
          name: "String"
        }
      },
      creationDate: {
        serializedName: "properties.creationDate",
        type: {
          name: "DateTime"
        }
      },
      formulaContent: {
        serializedName: "properties.formulaContent",
        type: {
          name: "Composite",
          className: "LabVirtualMachine"
        }
      },
      vm: {
        serializedName: "properties.vm",
        type: {
          name: "Composite",
          className: "FormulaPropertiesFromVm"
        }
      },
      provisioningState: {
        serializedName: "properties.provisioningState",
        type: {
          name: "String"
        }
      },
      id: {
        serializedName: "id",
        type: {
          name: "String"
        }
      },
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      type: {
        serializedName: "type",
        type: {
          name: "String"
        }
      },
      location: {
        serializedName: "location",
        type: {
          name: "String"
        }
      },
      tags: {
        serializedName: "tags",
        type: {
          name: "Dictionary",
          value: {
            type: {
              name: "String"
            }
          }
        }
      }
    }
  }
};

export const GalleryImage: msRest.CompositeMapper = {
  serializedName: "GalleryImage",
  type: {
    name: "Composite",
    className: "GalleryImage",
    modelProperties: {
      author: {
        serializedName: "properties.author",
        type: {
          name: "String"
        }
      },
      createdDate: {
        serializedName: "properties.createdDate",
        type: {
          name: "DateTime"
        }
      },
      description: {
        serializedName: "properties.description",
        type: {
          name: "String"
        }
      },
      imageReference: {
        serializedName: "properties.imageReference",
        type: {
          name: "Composite",
          className: "GalleryImageReference"
        }
      },
      icon: {
        serializedName: "properties.icon",
        type: {
          name: "String"
        }
      },
      enabled: {
        serializedName: "properties.enabled",
        type: {
          name: "Boolean"
        }
      },
      id: {
        serializedName: "id",
        type: {
          name: "String"
        }
      },
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      type: {
        serializedName: "type",
        type: {
          name: "String"
        }
      },
      location: {
        serializedName: "location",
        type: {
          name: "String"
        }
      },
      tags: {
        serializedName: "tags",
        type: {
          name: "Dictionary",
          value: {
            type: {
              name: "String"
            }
          }
        }
      }
    }
  }
};

export const ParameterInfo: msRest.CompositeMapper = {
  serializedName: "ParameterInfo",
  type: {
    name: "Composite",
    className: "ParameterInfo",
    modelProperties: {
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      value: {
        serializedName: "value",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const GenerateArmTemplateRequest: msRest.CompositeMapper = {
  serializedName: "GenerateArmTemplateRequest",
  type: {
    name: "Composite",
    className: "GenerateArmTemplateRequest",
    modelProperties: {
      virtualMachineName: {
        serializedName: "virtualMachineName",
        type: {
          name: "String"
        }
      },
      parameters: {
        serializedName: "parameters",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "ParameterInfo"
            }
          }
        }
      },
      location: {
        serializedName: "location",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const GenerateUploadUriParameter: msRest.CompositeMapper = {
  serializedName: "GenerateUploadUriParameter",
  type: {
    name: "Composite",
    className: "GenerateUploadUriParameter",
    modelProperties: {
      blobName: {
        serializedName: "blobName",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const GenerateUploadUriResponse: msRest.CompositeMapper = {
  serializedName: "GenerateUploadUriResponse",
  type: {
    name: "Composite",
    className: "GenerateUploadUriResponse",
    modelProperties: {
      uploadUri: {
        serializedName: "uploadUri",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const HourDetails: msRest.CompositeMapper = {
  serializedName: "HourDetails",
  type: {
    name: "Composite",
    className: "HourDetails",
    modelProperties: {
      minute: {
        serializedName: "minute",
        type: {
          name: "Number"
        }
      }
    }
  }
};

export const Lab: msRest.CompositeMapper = {
  serializedName: "Lab",
  type: {
    name: "Composite",
    className: "Lab",
    modelProperties: {
      defaultStorageAccount: {
        serializedName: "properties.defaultStorageAccount",
        type: {
          name: "String"
        }
      },
      artifactsStorageAccount: {
        serializedName: "properties.artifactsStorageAccount",
        type: {
          name: "String"
        }
      },
      storageAccounts: {
        serializedName: "properties.storageAccounts",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "String"
            }
          }
        }
      },
      vaultName: {
        serializedName: "properties.vaultName",
        type: {
          name: "String"
        }
      },
      labStorageType: {
        serializedName: "properties.labStorageType",
        type: {
          name: "String"
        }
      },
      defaultVirtualNetworkId: {
        serializedName: "properties.defaultVirtualNetworkId",
        type: {
          name: "String"
        }
      },
      createdDate: {
        serializedName: "properties.createdDate",
        type: {
          name: "DateTime"
        }
      },
      provisioningState: {
        serializedName: "properties.provisioningState",
        type: {
          name: "String"
        }
      },
      id: {
        serializedName: "id",
        type: {
          name: "String"
        }
      },
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      type: {
        serializedName: "type",
        type: {
          name: "String"
        }
      },
      location: {
        serializedName: "location",
        type: {
          name: "String"
        }
      },
      tags: {
        serializedName: "tags",
        type: {
          name: "Dictionary",
          value: {
            type: {
              name: "String"
            }
          }
        }
      }
    }
  }
};

export const LabVhd: msRest.CompositeMapper = {
  serializedName: "LabVhd",
  type: {
    name: "Composite",
    className: "LabVhd",
    modelProperties: {
      id: {
        serializedName: "id",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const Policy: msRest.CompositeMapper = {
  serializedName: "Policy",
  type: {
    name: "Composite",
    className: "Policy",
    modelProperties: {
      description: {
        serializedName: "properties.description",
        type: {
          name: "String"
        }
      },
      status: {
        serializedName: "properties.status",
        type: {
          name: "String"
        }
      },
      factName: {
        serializedName: "properties.factName",
        type: {
          name: "String"
        }
      },
      factData: {
        serializedName: "properties.factData",
        type: {
          name: "String"
        }
      },
      threshold: {
        serializedName: "properties.threshold",
        type: {
          name: "String"
        }
      },
      evaluatorType: {
        serializedName: "properties.evaluatorType",
        type: {
          name: "String"
        }
      },
      provisioningState: {
        serializedName: "properties.provisioningState",
        type: {
          name: "String"
        }
      },
      id: {
        serializedName: "id",
        type: {
          name: "String"
        }
      },
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      type: {
        serializedName: "type",
        type: {
          name: "String"
        }
      },
      location: {
        serializedName: "location",
        type: {
          name: "String"
        }
      },
      tags: {
        serializedName: "tags",
        type: {
          name: "Dictionary",
          value: {
            type: {
              name: "String"
            }
          }
        }
      }
    }
  }
};

export const WeekDetails: msRest.CompositeMapper = {
  serializedName: "WeekDetails",
  type: {
    name: "Composite",
    className: "WeekDetails",
    modelProperties: {
      weekdays: {
        serializedName: "weekdays",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "String"
            }
          }
        }
      },
      time: {
        serializedName: "time",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const Schedule: msRest.CompositeMapper = {
  serializedName: "Schedule",
  type: {
    name: "Composite",
    className: "Schedule",
    modelProperties: {
      status: {
        serializedName: "properties.status",
        type: {
          name: "String"
        }
      },
      taskType: {
        serializedName: "properties.taskType",
        type: {
          name: "String"
        }
      },
      weeklyRecurrence: {
        serializedName: "properties.weeklyRecurrence",
        type: {
          name: "Composite",
          className: "WeekDetails"
        }
      },
      dailyRecurrence: {
        serializedName: "properties.dailyRecurrence",
        type: {
          name: "Composite",
          className: "DayDetails"
        }
      },
      hourlyRecurrence: {
        serializedName: "properties.hourlyRecurrence",
        type: {
          name: "Composite",
          className: "HourDetails"
        }
      },
      timeZoneId: {
        serializedName: "properties.timeZoneId",
        type: {
          name: "String"
        }
      },
      provisioningState: {
        serializedName: "properties.provisioningState",
        type: {
          name: "String"
        }
      },
      id: {
        serializedName: "id",
        type: {
          name: "String"
        }
      },
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      type: {
        serializedName: "type",
        type: {
          name: "String"
        }
      },
      location: {
        serializedName: "location",
        type: {
          name: "String"
        }
      },
      tags: {
        serializedName: "tags",
        type: {
          name: "Dictionary",
          value: {
            type: {
              name: "String"
            }
          }
        }
      }
    }
  }
};

export const Subnet: msRest.CompositeMapper = {
  serializedName: "Subnet",
  type: {
    name: "Composite",
    className: "Subnet",
    modelProperties: {
      resourceId: {
        serializedName: "resourceId",
        type: {
          name: "String"
        }
      },
      labSubnetName: {
        serializedName: "labSubnetName",
        type: {
          name: "String"
        }
      },
      allowPublicIp: {
        serializedName: "allowPublicIp",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const SubnetOverride: msRest.CompositeMapper = {
  serializedName: "SubnetOverride",
  type: {
    name: "Composite",
    className: "SubnetOverride",
    modelProperties: {
      resourceId: {
        serializedName: "resourceId",
        type: {
          name: "String"
        }
      },
      labSubnetName: {
        serializedName: "labSubnetName",
        type: {
          name: "String"
        }
      },
      useInVmCreationPermission: {
        serializedName: "useInVmCreationPermission",
        type: {
          name: "String"
        }
      },
      usePublicIpAddressPermission: {
        serializedName: "usePublicIpAddressPermission",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const SubscriptionNotificationProperties: msRest.CompositeMapper = {
  serializedName: "SubscriptionNotificationProperties",
  type: {
    name: "Composite",
    className: "SubscriptionNotificationProperties",
    modelProperties: {
      tenantId: {
        serializedName: "tenantId",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const SubscriptionNotification: msRest.CompositeMapper = {
  serializedName: "SubscriptionNotification",
  type: {
    name: "Composite",
    className: "SubscriptionNotification",
    modelProperties: {
      registrationDate: {
        serializedName: "registrationDate",
        type: {
          name: "String"
        }
      },
      state: {
        serializedName: "state",
        type: {
          name: "String"
        }
      },
      properties: {
        serializedName: "properties",
        type: {
          name: "Composite",
          className: "SubscriptionNotificationProperties"
        }
      }
    }
  }
};

export const VirtualNetwork: msRest.CompositeMapper = {
  serializedName: "VirtualNetwork",
  type: {
    name: "Composite",
    className: "VirtualNetwork",
    modelProperties: {
      allowedSubnets: {
        serializedName: "properties.allowedSubnets",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "Subnet"
            }
          }
        }
      },
      description: {
        serializedName: "properties.description",
        type: {
          name: "String"
        }
      },
      externalProviderResourceId: {
        serializedName: "properties.externalProviderResourceId",
        type: {
          name: "String"
        }
      },
      subnetOverrides: {
        serializedName: "properties.subnetOverrides",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "SubnetOverride"
            }
          }
        }
      },
      provisioningState: {
        serializedName: "properties.provisioningState",
        type: {
          name: "String"
        }
      },
      id: {
        serializedName: "id",
        type: {
          name: "String"
        }
      },
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      type: {
        serializedName: "type",
        type: {
          name: "String"
        }
      },
      location: {
        serializedName: "location",
        type: {
          name: "String"
        }
      },
      tags: {
        serializedName: "tags",
        type: {
          name: "Dictionary",
          value: {
            type: {
              name: "String"
            }
          }
        }
      }
    }
  }
};

export const ResponseWithContinuationLab: msRest.CompositeMapper = {
  serializedName: "ResponseWithContinuation_Lab_",
  type: {
    name: "Composite",
    className: "ResponseWithContinuationLab",
    modelProperties: {
      value: {
        serializedName: "",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "Lab"
            }
          }
        }
      },
      nextLink: {
        serializedName: "nextLink",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const ResponseWithContinuationLabVhd: msRest.CompositeMapper = {
  serializedName: "ResponseWithContinuation_LabVhd_",
  type: {
    name: "Composite",
    className: "ResponseWithContinuationLabVhd",
    modelProperties: {
      value: {
        serializedName: "",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "LabVhd"
            }
          }
        }
      },
      nextLink: {
        serializedName: "nextLink",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const ResponseWithContinuationArtifactSource: msRest.CompositeMapper = {
  serializedName: "ResponseWithContinuation_ArtifactSource_",
  type: {
    name: "Composite",
    className: "ResponseWithContinuationArtifactSource",
    modelProperties: {
      value: {
        serializedName: "",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "ArtifactSource"
            }
          }
        }
      },
      nextLink: {
        serializedName: "nextLink",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const ResponseWithContinuationArtifact: msRest.CompositeMapper = {
  serializedName: "ResponseWithContinuation_Artifact_",
  type: {
    name: "Composite",
    className: "ResponseWithContinuationArtifact",
    modelProperties: {
      value: {
        serializedName: "",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "Artifact"
            }
          }
        }
      },
      nextLink: {
        serializedName: "nextLink",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const ResponseWithContinuationCostInsight: msRest.CompositeMapper = {
  serializedName: "ResponseWithContinuation_CostInsight_",
  type: {
    name: "Composite",
    className: "ResponseWithContinuationCostInsight",
    modelProperties: {
      value: {
        serializedName: "",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "CostInsight"
            }
          }
        }
      },
      nextLink: {
        serializedName: "nextLink",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const ResponseWithContinuationCost: msRest.CompositeMapper = {
  serializedName: "ResponseWithContinuation_Cost_",
  type: {
    name: "Composite",
    className: "ResponseWithContinuationCost",
    modelProperties: {
      value: {
        serializedName: "",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "Cost"
            }
          }
        }
      },
      nextLink: {
        serializedName: "nextLink",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const ResponseWithContinuationCustomImage: msRest.CompositeMapper = {
  serializedName: "ResponseWithContinuation_CustomImage_",
  type: {
    name: "Composite",
    className: "ResponseWithContinuationCustomImage",
    modelProperties: {
      value: {
        serializedName: "",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "CustomImage"
            }
          }
        }
      },
      nextLink: {
        serializedName: "nextLink",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const ResponseWithContinuationFormula: msRest.CompositeMapper = {
  serializedName: "ResponseWithContinuation_Formula_",
  type: {
    name: "Composite",
    className: "ResponseWithContinuationFormula",
    modelProperties: {
      value: {
        serializedName: "",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "Formula"
            }
          }
        }
      },
      nextLink: {
        serializedName: "nextLink",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const ResponseWithContinuationGalleryImage: msRest.CompositeMapper = {
  serializedName: "ResponseWithContinuation_GalleryImage_",
  type: {
    name: "Composite",
    className: "ResponseWithContinuationGalleryImage",
    modelProperties: {
      value: {
        serializedName: "",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "GalleryImage"
            }
          }
        }
      },
      nextLink: {
        serializedName: "nextLink",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const ResponseWithContinuationPolicy: msRest.CompositeMapper = {
  serializedName: "ResponseWithContinuation_Policy_",
  type: {
    name: "Composite",
    className: "ResponseWithContinuationPolicy",
    modelProperties: {
      value: {
        serializedName: "",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "Policy"
            }
          }
        }
      },
      nextLink: {
        serializedName: "nextLink",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const ResponseWithContinuationSchedule: msRest.CompositeMapper = {
  serializedName: "ResponseWithContinuation_Schedule_",
  type: {
    name: "Composite",
    className: "ResponseWithContinuationSchedule",
    modelProperties: {
      value: {
        serializedName: "",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "Schedule"
            }
          }
        }
      },
      nextLink: {
        serializedName: "nextLink",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const ResponseWithContinuationLabVirtualMachine: msRest.CompositeMapper = {
  serializedName: "ResponseWithContinuation_LabVirtualMachine_",
  type: {
    name: "Composite",
    className: "ResponseWithContinuationLabVirtualMachine",
    modelProperties: {
      value: {
        serializedName: "",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "LabVirtualMachine"
            }
          }
        }
      },
      nextLink: {
        serializedName: "nextLink",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const ResponseWithContinuationVirtualNetwork: msRest.CompositeMapper = {
  serializedName: "ResponseWithContinuation_VirtualNetwork_",
  type: {
    name: "Composite",
    className: "ResponseWithContinuationVirtualNetwork",
    modelProperties: {
      value: {
        serializedName: "",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "VirtualNetwork"
            }
          }
        }
      },
      nextLink: {
        serializedName: "nextLink",
        type: {
          name: "String"
        }
      }
    }
  }
};
