/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "ms-rest-js";
import * as Models from "./models";
import * as Mappers from "./models/mappers";
import * as operations from "./operations";
import { AutomationClientContext } from "./automationClientContext";


class AutomationClient extends AutomationClientContext {
  // Operation groups
  python2Package: operations.Python2Package;
  runbookDraft: operations.RunbookDraftOperations;
  runbook: operations.RunbookOperations;
  testJobStreams: operations.TestJobStreams;
  testJob: operations.TestJobOperations;

  /**
   * Initializes a new instance of the AutomationClient class.
   * @param credentials Credentials needed for the client to connect to Azure.
   * @param subscriptionId Gets subscription credentials which uniquely identify Microsoft Azure
   * subscription. The subscription ID forms part of the URI for every service call.
   * @param [options] The parameter options
   */
  constructor(credentials: msRest.ServiceClientCredentials, subscriptionId: string, options?: Models.AutomationClientOptions) {
    super(credentials, subscriptionId, options);
    this.python2Package = new operations.Python2Package(this);
    this.runbookDraft = new operations.RunbookDraftOperations(this);
    this.runbook = new operations.RunbookOperations(this);
    this.testJobStreams = new operations.TestJobStreams(this);
    this.testJob = new operations.TestJobOperations(this);
  }
}

// Operation Specifications

export {
  AutomationClient,
  AutomationClientContext,
  Models as AutomationModels,
  Mappers as AutomationMappers
};
export * from "./operations";
