/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "ms-rest-js";
import * as Models from "../models";
import * as Mappers from "../models/artifactSourceOperationsMappers";
import * as Parameters from "../models/parameters";
import { DevTestLabsClientContext } from "../devTestLabsClientContext";

/** Class representing a ArtifactSourceOperations. */
export class ArtifactSourceOperations {
  private readonly client: DevTestLabsClientContext;

  /**
   * Create a ArtifactSourceOperations.
   * @param {DevTestLabsClientContext} client Reference to the service client.
   */
  constructor(client: DevTestLabsClientContext) {
    this.client = client;
  }

  /**
   * List artifact sources.
   * @param resourceGroupName The name of the resource group.
   * @param labName The name of the lab.
   * @param [options] The optional parameters
   * @returns Promise<Models.ArtifactSourceListResponse>
   */
  list(resourceGroupName: string, labName: string, options?: Models.ArtifactSourceListOptionalParams): Promise<Models.ArtifactSourceListResponse>;
  /**
   * @param resourceGroupName The name of the resource group.
   * @param labName The name of the lab.
   * @param callback The callback
   */
  list(resourceGroupName: string, labName: string, callback: msRest.ServiceCallback<Models.ResponseWithContinuationArtifactSource>): void;
  /**
   * @param resourceGroupName The name of the resource group.
   * @param labName The name of the lab.
   * @param options The optional parameters
   * @param callback The callback
   */
  list(resourceGroupName: string, labName: string, options: Models.ArtifactSourceListOptionalParams, callback: msRest.ServiceCallback<Models.ResponseWithContinuationArtifactSource>): void;
  list(resourceGroupName: string, labName: string, options?: Models.ArtifactSourceListOptionalParams, callback?: msRest.ServiceCallback<Models.ResponseWithContinuationArtifactSource>): Promise<Models.ArtifactSourceListResponse> {
    return this.client.sendOperationRequest(
      {
        resourceGroupName,
        labName,
        options
      },
      listOperationSpec,
      callback) as Promise<Models.ArtifactSourceListResponse>;
  }

  /**
   * Get artifact source.
   * @param resourceGroupName The name of the resource group.
   * @param labName The name of the lab.
   * @param name The name of the artifact source.
   * @param [options] The optional parameters
   * @returns Promise<Models.ArtifactSourceGetResourceResponse>
   */
  getResource(resourceGroupName: string, labName: string, name: string, options?: msRest.RequestOptionsBase): Promise<Models.ArtifactSourceGetResourceResponse>;
  /**
   * @param resourceGroupName The name of the resource group.
   * @param labName The name of the lab.
   * @param name The name of the artifact source.
   * @param callback The callback
   */
  getResource(resourceGroupName: string, labName: string, name: string, callback: msRest.ServiceCallback<Models.ArtifactSource>): void;
  /**
   * @param resourceGroupName The name of the resource group.
   * @param labName The name of the lab.
   * @param name The name of the artifact source.
   * @param options The optional parameters
   * @param callback The callback
   */
  getResource(resourceGroupName: string, labName: string, name: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.ArtifactSource>): void;
  getResource(resourceGroupName: string, labName: string, name: string, options?: msRest.RequestOptionsBase, callback?: msRest.ServiceCallback<Models.ArtifactSource>): Promise<Models.ArtifactSourceGetResourceResponse> {
    return this.client.sendOperationRequest(
      {
        resourceGroupName,
        labName,
        name,
        options
      },
      getResourceOperationSpec,
      callback) as Promise<Models.ArtifactSourceGetResourceResponse>;
  }

  /**
   * Create or replace an existing artifact source.
   * @param resourceGroupName The name of the resource group.
   * @param labName The name of the lab.
   * @param name The name of the artifact source.
   * @param artifactSource
   * @param [options] The optional parameters
   * @returns Promise<Models.ArtifactSourceCreateOrUpdateResourceResponse>
   */
  createOrUpdateResource(resourceGroupName: string, labName: string, name: string, artifactSource: Models.ArtifactSource, options?: msRest.RequestOptionsBase): Promise<Models.ArtifactSourceCreateOrUpdateResourceResponse>;
  /**
   * @param resourceGroupName The name of the resource group.
   * @param labName The name of the lab.
   * @param name The name of the artifact source.
   * @param artifactSource
   * @param callback The callback
   */
  createOrUpdateResource(resourceGroupName: string, labName: string, name: string, artifactSource: Models.ArtifactSource, callback: msRest.ServiceCallback<Models.ArtifactSource>): void;
  /**
   * @param resourceGroupName The name of the resource group.
   * @param labName The name of the lab.
   * @param name The name of the artifact source.
   * @param artifactSource
   * @param options The optional parameters
   * @param callback The callback
   */
  createOrUpdateResource(resourceGroupName: string, labName: string, name: string, artifactSource: Models.ArtifactSource, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.ArtifactSource>): void;
  createOrUpdateResource(resourceGroupName: string, labName: string, name: string, artifactSource: Models.ArtifactSource, options?: msRest.RequestOptionsBase, callback?: msRest.ServiceCallback<Models.ArtifactSource>): Promise<Models.ArtifactSourceCreateOrUpdateResourceResponse> {
    return this.client.sendOperationRequest(
      {
        resourceGroupName,
        labName,
        name,
        artifactSource,
        options
      },
      createOrUpdateResourceOperationSpec,
      callback) as Promise<Models.ArtifactSourceCreateOrUpdateResourceResponse>;
  }

  /**
   * Delete artifact source.
   * @param resourceGroupName The name of the resource group.
   * @param labName The name of the lab.
   * @param name The name of the artifact source.
   * @param [options] The optional parameters
   * @returns Promise<msRest.RestResponse>
   */
  deleteResource(resourceGroupName: string, labName: string, name: string, options?: msRest.RequestOptionsBase): Promise<msRest.RestResponse>;
  /**
   * @param resourceGroupName The name of the resource group.
   * @param labName The name of the lab.
   * @param name The name of the artifact source.
   * @param callback The callback
   */
  deleteResource(resourceGroupName: string, labName: string, name: string, callback: msRest.ServiceCallback<void>): void;
  /**
   * @param resourceGroupName The name of the resource group.
   * @param labName The name of the lab.
   * @param name The name of the artifact source.
   * @param options The optional parameters
   * @param callback The callback
   */
  deleteResource(resourceGroupName: string, labName: string, name: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<void>): void;
  deleteResource(resourceGroupName: string, labName: string, name: string, options?: msRest.RequestOptionsBase, callback?: msRest.ServiceCallback<void>): Promise<msRest.RestResponse> {
    return this.client.sendOperationRequest(
      {
        resourceGroupName,
        labName,
        name,
        options
      },
      deleteResourceOperationSpec,
      callback);
  }

  /**
   * Modify properties of artifact sources.
   * @param resourceGroupName The name of the resource group.
   * @param labName The name of the lab.
   * @param name The name of the artifact source.
   * @param artifactSource
   * @param [options] The optional parameters
   * @returns Promise<Models.ArtifactSourcePatchResourceResponse>
   */
  patchResource(resourceGroupName: string, labName: string, name: string, artifactSource: Models.ArtifactSource, options?: msRest.RequestOptionsBase): Promise<Models.ArtifactSourcePatchResourceResponse>;
  /**
   * @param resourceGroupName The name of the resource group.
   * @param labName The name of the lab.
   * @param name The name of the artifact source.
   * @param artifactSource
   * @param callback The callback
   */
  patchResource(resourceGroupName: string, labName: string, name: string, artifactSource: Models.ArtifactSource, callback: msRest.ServiceCallback<Models.ArtifactSource>): void;
  /**
   * @param resourceGroupName The name of the resource group.
   * @param labName The name of the lab.
   * @param name The name of the artifact source.
   * @param artifactSource
   * @param options The optional parameters
   * @param callback The callback
   */
  patchResource(resourceGroupName: string, labName: string, name: string, artifactSource: Models.ArtifactSource, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.ArtifactSource>): void;
  patchResource(resourceGroupName: string, labName: string, name: string, artifactSource: Models.ArtifactSource, options?: msRest.RequestOptionsBase, callback?: msRest.ServiceCallback<Models.ArtifactSource>): Promise<Models.ArtifactSourcePatchResourceResponse> {
    return this.client.sendOperationRequest(
      {
        resourceGroupName,
        labName,
        name,
        artifactSource,
        options
      },
      patchResourceOperationSpec,
      callback) as Promise<Models.ArtifactSourcePatchResourceResponse>;
  }

  /**
   * List artifact sources.
   * @param nextPageLink The NextLink from the previous successful call to List operation.
   * @param [options] The optional parameters
   * @returns Promise<Models.ArtifactSourceListNextResponse>
   */
  listNext(nextPageLink: string, options?: msRest.RequestOptionsBase): Promise<Models.ArtifactSourceListNextResponse>;
  /**
   * @param nextPageLink The NextLink from the previous successful call to List operation.
   * @param callback The callback
   */
  listNext(nextPageLink: string, callback: msRest.ServiceCallback<Models.ResponseWithContinuationArtifactSource>): void;
  /**
   * @param nextPageLink The NextLink from the previous successful call to List operation.
   * @param options The optional parameters
   * @param callback The callback
   */
  listNext(nextPageLink: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.ResponseWithContinuationArtifactSource>): void;
  listNext(nextPageLink: string, options?: msRest.RequestOptionsBase, callback?: msRest.ServiceCallback<Models.ResponseWithContinuationArtifactSource>): Promise<Models.ArtifactSourceListNextResponse> {
    return this.client.sendOperationRequest(
      {
        nextPageLink,
        options
      },
      listNextOperationSpec,
      callback) as Promise<Models.ArtifactSourceListNextResponse>;
  }
}

// Operation Specifications
const serializer = new msRest.Serializer(Mappers);
const listOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DevTestLab/labs/{labName}/artifactsources",
  urlParameters: [
    Parameters.subscriptionId,
    Parameters.resourceGroupName,
    Parameters.labName
  ],
  queryParameters: [
    Parameters.filter,
    Parameters.top,
    Parameters.orderBy,
    Parameters.apiVersion
  ],
  headerParameters: [
    Parameters.acceptLanguage
  ],
  responses: {
    200: {
      bodyMapper: Mappers.ResponseWithContinuationArtifactSource
    },
    default: {
      bodyMapper: Mappers.CloudError
    }
  },
  serializer
};

const getResourceOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DevTestLab/labs/{labName}/artifactsources/{name}",
  urlParameters: [
    Parameters.subscriptionId,
    Parameters.resourceGroupName,
    Parameters.labName,
    Parameters.name
  ],
  queryParameters: [
    Parameters.apiVersion
  ],
  headerParameters: [
    Parameters.acceptLanguage
  ],
  responses: {
    200: {
      bodyMapper: Mappers.ArtifactSource
    },
    default: {
      bodyMapper: Mappers.CloudError
    }
  },
  serializer
};

const createOrUpdateResourceOperationSpec: msRest.OperationSpec = {
  httpMethod: "PUT",
  path: "subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DevTestLab/labs/{labName}/artifactsources/{name}",
  urlParameters: [
    Parameters.subscriptionId,
    Parameters.resourceGroupName,
    Parameters.labName,
    Parameters.name
  ],
  queryParameters: [
    Parameters.apiVersion
  ],
  headerParameters: [
    Parameters.acceptLanguage
  ],
  requestBody: {
    parameterPath: "artifactSource",
    mapper: {
      ...Mappers.ArtifactSource,
      required: true
    }
  },
  responses: {
    200: {
      bodyMapper: Mappers.ArtifactSource
    },
    201: {
      bodyMapper: Mappers.ArtifactSource
    },
    default: {
      bodyMapper: Mappers.CloudError
    }
  },
  serializer
};

const deleteResourceOperationSpec: msRest.OperationSpec = {
  httpMethod: "DELETE",
  path: "subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DevTestLab/labs/{labName}/artifactsources/{name}",
  urlParameters: [
    Parameters.subscriptionId,
    Parameters.resourceGroupName,
    Parameters.labName,
    Parameters.name
  ],
  queryParameters: [
    Parameters.apiVersion
  ],
  headerParameters: [
    Parameters.acceptLanguage
  ],
  responses: {
    200: {},
    204: {},
    default: {
      bodyMapper: Mappers.CloudError
    }
  },
  serializer
};

const patchResourceOperationSpec: msRest.OperationSpec = {
  httpMethod: "PATCH",
  path: "subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DevTestLab/labs/{labName}/artifactsources/{name}",
  urlParameters: [
    Parameters.subscriptionId,
    Parameters.resourceGroupName,
    Parameters.labName,
    Parameters.name
  ],
  queryParameters: [
    Parameters.apiVersion
  ],
  headerParameters: [
    Parameters.acceptLanguage
  ],
  requestBody: {
    parameterPath: "artifactSource",
    mapper: {
      ...Mappers.ArtifactSource,
      required: true
    }
  },
  responses: {
    200: {
      bodyMapper: Mappers.ArtifactSource
    },
    default: {
      bodyMapper: Mappers.CloudError
    }
  },
  serializer
};

const listNextOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  baseUrl: "https://management.azure.com",
  path: "{nextLink}",
  urlParameters: [
    Parameters.nextPageLink
  ],
  headerParameters: [
    Parameters.acceptLanguage
  ],
  responses: {
    200: {
      bodyMapper: Mappers.ResponseWithContinuationArtifactSource
    },
    default: {
      bodyMapper: Mappers.CloudError
    }
  },
  serializer
};
