/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "ms-rest-js";
import * as Models from "../models";
import * as Mappers from "../models/artifactOperationsMappers";
import * as Parameters from "../models/parameters";
import { DevTestLabsClientContext } from "../devTestLabsClientContext";

/** Class representing a ArtifactOperations. */
export class ArtifactOperations {
  private readonly client: DevTestLabsClientContext;

  /**
   * Create a ArtifactOperations.
   * @param {DevTestLabsClientContext} client Reference to the service client.
   */
  constructor(client: DevTestLabsClientContext) {
    this.client = client;
  }

  /**
   * List artifacts.
   * @param resourceGroupName The name of the resource group.
   * @param labName The name of the lab.
   * @param artifactSourceName The name of the artifact source.
   * @param [options] The optional parameters
   * @returns Promise<Models.ArtifactListResponse>
   */
  list(resourceGroupName: string, labName: string, artifactSourceName: string, options?: Models.ArtifactListOptionalParams): Promise<Models.ArtifactListResponse>;
  /**
   * @param resourceGroupName The name of the resource group.
   * @param labName The name of the lab.
   * @param artifactSourceName The name of the artifact source.
   * @param callback The callback
   */
  list(resourceGroupName: string, labName: string, artifactSourceName: string, callback: msRest.ServiceCallback<Models.ResponseWithContinuationArtifact>): void;
  /**
   * @param resourceGroupName The name of the resource group.
   * @param labName The name of the lab.
   * @param artifactSourceName The name of the artifact source.
   * @param options The optional parameters
   * @param callback The callback
   */
  list(resourceGroupName: string, labName: string, artifactSourceName: string, options: Models.ArtifactListOptionalParams, callback: msRest.ServiceCallback<Models.ResponseWithContinuationArtifact>): void;
  list(resourceGroupName: string, labName: string, artifactSourceName: string, options?: Models.ArtifactListOptionalParams, callback?: msRest.ServiceCallback<Models.ResponseWithContinuationArtifact>): Promise<Models.ArtifactListResponse> {
    return this.client.sendOperationRequest(
      {
        resourceGroupName,
        labName,
        artifactSourceName,
        options
      },
      listOperationSpec,
      callback) as Promise<Models.ArtifactListResponse>;
  }

  /**
   * Get artifact.
   * @param resourceGroupName The name of the resource group.
   * @param labName The name of the lab.
   * @param artifactSourceName The name of the artifact source.
   * @param name The name of the artifact.
   * @param [options] The optional parameters
   * @returns Promise<Models.ArtifactGetResourceResponse>
   */
  getResource(resourceGroupName: string, labName: string, artifactSourceName: string, name: string, options?: msRest.RequestOptionsBase): Promise<Models.ArtifactGetResourceResponse>;
  /**
   * @param resourceGroupName The name of the resource group.
   * @param labName The name of the lab.
   * @param artifactSourceName The name of the artifact source.
   * @param name The name of the artifact.
   * @param callback The callback
   */
  getResource(resourceGroupName: string, labName: string, artifactSourceName: string, name: string, callback: msRest.ServiceCallback<Models.Artifact>): void;
  /**
   * @param resourceGroupName The name of the resource group.
   * @param labName The name of the lab.
   * @param artifactSourceName The name of the artifact source.
   * @param name The name of the artifact.
   * @param options The optional parameters
   * @param callback The callback
   */
  getResource(resourceGroupName: string, labName: string, artifactSourceName: string, name: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.Artifact>): void;
  getResource(resourceGroupName: string, labName: string, artifactSourceName: string, name: string, options?: msRest.RequestOptionsBase, callback?: msRest.ServiceCallback<Models.Artifact>): Promise<Models.ArtifactGetResourceResponse> {
    return this.client.sendOperationRequest(
      {
        resourceGroupName,
        labName,
        artifactSourceName,
        name,
        options
      },
      getResourceOperationSpec,
      callback) as Promise<Models.ArtifactGetResourceResponse>;
  }

  /**
   * Generates an ARM template for the given artifact, uploads the required files to a storage
   * account, and validates the generated artifact.
   * @param resourceGroupName The name of the resource group.
   * @param labName The name of the lab.
   * @param artifactSourceName The name of the artifact source.
   * @param name The name of the artifact.
   * @param generateArmTemplateRequest
   * @param [options] The optional parameters
   * @returns Promise<Models.ArtifactGenerateArmTemplateResponse>
   */
  generateArmTemplate(resourceGroupName: string, labName: string, artifactSourceName: string, name: string, generateArmTemplateRequest: Models.GenerateArmTemplateRequest, options?: msRest.RequestOptionsBase): Promise<Models.ArtifactGenerateArmTemplateResponse>;
  /**
   * @param resourceGroupName The name of the resource group.
   * @param labName The name of the lab.
   * @param artifactSourceName The name of the artifact source.
   * @param name The name of the artifact.
   * @param generateArmTemplateRequest
   * @param callback The callback
   */
  generateArmTemplate(resourceGroupName: string, labName: string, artifactSourceName: string, name: string, generateArmTemplateRequest: Models.GenerateArmTemplateRequest, callback: msRest.ServiceCallback<Models.ArmTemplateInfo>): void;
  /**
   * @param resourceGroupName The name of the resource group.
   * @param labName The name of the lab.
   * @param artifactSourceName The name of the artifact source.
   * @param name The name of the artifact.
   * @param generateArmTemplateRequest
   * @param options The optional parameters
   * @param callback The callback
   */
  generateArmTemplate(resourceGroupName: string, labName: string, artifactSourceName: string, name: string, generateArmTemplateRequest: Models.GenerateArmTemplateRequest, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.ArmTemplateInfo>): void;
  generateArmTemplate(resourceGroupName: string, labName: string, artifactSourceName: string, name: string, generateArmTemplateRequest: Models.GenerateArmTemplateRequest, options?: msRest.RequestOptionsBase, callback?: msRest.ServiceCallback<Models.ArmTemplateInfo>): Promise<Models.ArtifactGenerateArmTemplateResponse> {
    return this.client.sendOperationRequest(
      {
        resourceGroupName,
        labName,
        artifactSourceName,
        name,
        generateArmTemplateRequest,
        options
      },
      generateArmTemplateOperationSpec,
      callback) as Promise<Models.ArtifactGenerateArmTemplateResponse>;
  }

  /**
   * List artifacts.
   * @param nextPageLink The NextLink from the previous successful call to List operation.
   * @param [options] The optional parameters
   * @returns Promise<Models.ArtifactListNextResponse>
   */
  listNext(nextPageLink: string, options?: msRest.RequestOptionsBase): Promise<Models.ArtifactListNextResponse>;
  /**
   * @param nextPageLink The NextLink from the previous successful call to List operation.
   * @param callback The callback
   */
  listNext(nextPageLink: string, callback: msRest.ServiceCallback<Models.ResponseWithContinuationArtifact>): void;
  /**
   * @param nextPageLink The NextLink from the previous successful call to List operation.
   * @param options The optional parameters
   * @param callback The callback
   */
  listNext(nextPageLink: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.ResponseWithContinuationArtifact>): void;
  listNext(nextPageLink: string, options?: msRest.RequestOptionsBase, callback?: msRest.ServiceCallback<Models.ResponseWithContinuationArtifact>): Promise<Models.ArtifactListNextResponse> {
    return this.client.sendOperationRequest(
      {
        nextPageLink,
        options
      },
      listNextOperationSpec,
      callback) as Promise<Models.ArtifactListNextResponse>;
  }
}

// Operation Specifications
const serializer = new msRest.Serializer(Mappers);
const listOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DevTestLab/labs/{labName}/artifactsources/{artifactSourceName}/artifacts",
  urlParameters: [
    Parameters.subscriptionId,
    Parameters.resourceGroupName,
    Parameters.labName,
    Parameters.artifactSourceName
  ],
  queryParameters: [
    Parameters.filter,
    Parameters.top,
    Parameters.orderBy,
    Parameters.apiVersion
  ],
  headerParameters: [
    Parameters.acceptLanguage
  ],
  responses: {
    200: {
      bodyMapper: Mappers.ResponseWithContinuationArtifact
    },
    default: {
      bodyMapper: Mappers.CloudError
    }
  },
  serializer
};

const getResourceOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DevTestLab/labs/{labName}/artifactsources/{artifactSourceName}/artifacts/{name}",
  urlParameters: [
    Parameters.subscriptionId,
    Parameters.resourceGroupName,
    Parameters.labName,
    Parameters.artifactSourceName,
    Parameters.name
  ],
  queryParameters: [
    Parameters.apiVersion
  ],
  headerParameters: [
    Parameters.acceptLanguage
  ],
  responses: {
    200: {
      bodyMapper: Mappers.Artifact
    },
    default: {
      bodyMapper: Mappers.CloudError
    }
  },
  serializer
};

const generateArmTemplateOperationSpec: msRest.OperationSpec = {
  httpMethod: "POST",
  path: "subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DevTestLab/labs/{labName}/artifactsources/{artifactSourceName}/artifacts/{name}/generateArmTemplate",
  urlParameters: [
    Parameters.subscriptionId,
    Parameters.resourceGroupName,
    Parameters.labName,
    Parameters.artifactSourceName,
    Parameters.name
  ],
  queryParameters: [
    Parameters.apiVersion
  ],
  headerParameters: [
    Parameters.acceptLanguage
  ],
  requestBody: {
    parameterPath: "generateArmTemplateRequest",
    mapper: {
      ...Mappers.GenerateArmTemplateRequest,
      required: true
    }
  },
  responses: {
    200: {
      bodyMapper: Mappers.ArmTemplateInfo
    },
    default: {
      bodyMapper: Mappers.CloudError
    }
  },
  serializer
};

const listNextOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  baseUrl: "https://management.azure.com",
  path: "{nextLink}",
  urlParameters: [
    Parameters.nextPageLink
  ],
  headerParameters: [
    Parameters.acceptLanguage
  ],
  responses: {
    200: {
      bodyMapper: Mappers.ResponseWithContinuationArtifact
    },
    default: {
      bodyMapper: Mappers.CloudError
    }
  },
  serializer
};
