/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "ms-rest-js";
import * as Models from "../models";
import * as Mappers from "../models/policyOperationsMappers";
import * as Parameters from "../models/parameters";
import { DevTestLabsClientContext } from "../devTestLabsClientContext";

/** Class representing a PolicyOperations. */
export class PolicyOperations {
  private readonly client: DevTestLabsClientContext;

  /**
   * Create a PolicyOperations.
   * @param {DevTestLabsClientContext} client Reference to the service client.
   */
  constructor(client: DevTestLabsClientContext) {
    this.client = client;
  }

  /**
   * List policies.
   * @param resourceGroupName The name of the resource group.
   * @param labName The name of the lab.
   * @param policySetName The name of the policy set.
   * @param [options] The optional parameters
   * @returns Promise<Models.PolicyListResponse>
   */
  list(resourceGroupName: string, labName: string, policySetName: string, options?: Models.PolicyListOptionalParams): Promise<Models.PolicyListResponse>;
  /**
   * @param resourceGroupName The name of the resource group.
   * @param labName The name of the lab.
   * @param policySetName The name of the policy set.
   * @param callback The callback
   */
  list(resourceGroupName: string, labName: string, policySetName: string, callback: msRest.ServiceCallback<Models.ResponseWithContinuationPolicy>): void;
  /**
   * @param resourceGroupName The name of the resource group.
   * @param labName The name of the lab.
   * @param policySetName The name of the policy set.
   * @param options The optional parameters
   * @param callback The callback
   */
  list(resourceGroupName: string, labName: string, policySetName: string, options: Models.PolicyListOptionalParams, callback: msRest.ServiceCallback<Models.ResponseWithContinuationPolicy>): void;
  list(resourceGroupName: string, labName: string, policySetName: string, options?: Models.PolicyListOptionalParams, callback?: msRest.ServiceCallback<Models.ResponseWithContinuationPolicy>): Promise<Models.PolicyListResponse> {
    return this.client.sendOperationRequest(
      {
        resourceGroupName,
        labName,
        policySetName,
        options
      },
      listOperationSpec,
      callback) as Promise<Models.PolicyListResponse>;
  }

  /**
   * Get policy.
   * @param resourceGroupName The name of the resource group.
   * @param labName The name of the lab.
   * @param policySetName The name of the policy set.
   * @param name The name of the policy.
   * @param [options] The optional parameters
   * @returns Promise<Models.PolicyGetResourceResponse>
   */
  getResource(resourceGroupName: string, labName: string, policySetName: string, name: string, options?: msRest.RequestOptionsBase): Promise<Models.PolicyGetResourceResponse>;
  /**
   * @param resourceGroupName The name of the resource group.
   * @param labName The name of the lab.
   * @param policySetName The name of the policy set.
   * @param name The name of the policy.
   * @param callback The callback
   */
  getResource(resourceGroupName: string, labName: string, policySetName: string, name: string, callback: msRest.ServiceCallback<Models.Policy>): void;
  /**
   * @param resourceGroupName The name of the resource group.
   * @param labName The name of the lab.
   * @param policySetName The name of the policy set.
   * @param name The name of the policy.
   * @param options The optional parameters
   * @param callback The callback
   */
  getResource(resourceGroupName: string, labName: string, policySetName: string, name: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.Policy>): void;
  getResource(resourceGroupName: string, labName: string, policySetName: string, name: string, options?: msRest.RequestOptionsBase, callback?: msRest.ServiceCallback<Models.Policy>): Promise<Models.PolicyGetResourceResponse> {
    return this.client.sendOperationRequest(
      {
        resourceGroupName,
        labName,
        policySetName,
        name,
        options
      },
      getResourceOperationSpec,
      callback) as Promise<Models.PolicyGetResourceResponse>;
  }

  /**
   * Create or replace an existing policy.
   * @param resourceGroupName The name of the resource group.
   * @param labName The name of the lab.
   * @param policySetName The name of the policy set.
   * @param name The name of the policy.
   * @param policy
   * @param [options] The optional parameters
   * @returns Promise<Models.PolicyCreateOrUpdateResourceResponse>
   */
  createOrUpdateResource(resourceGroupName: string, labName: string, policySetName: string, name: string, policy: Models.Policy, options?: msRest.RequestOptionsBase): Promise<Models.PolicyCreateOrUpdateResourceResponse>;
  /**
   * @param resourceGroupName The name of the resource group.
   * @param labName The name of the lab.
   * @param policySetName The name of the policy set.
   * @param name The name of the policy.
   * @param policy
   * @param callback The callback
   */
  createOrUpdateResource(resourceGroupName: string, labName: string, policySetName: string, name: string, policy: Models.Policy, callback: msRest.ServiceCallback<Models.Policy>): void;
  /**
   * @param resourceGroupName The name of the resource group.
   * @param labName The name of the lab.
   * @param policySetName The name of the policy set.
   * @param name The name of the policy.
   * @param policy
   * @param options The optional parameters
   * @param callback The callback
   */
  createOrUpdateResource(resourceGroupName: string, labName: string, policySetName: string, name: string, policy: Models.Policy, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.Policy>): void;
  createOrUpdateResource(resourceGroupName: string, labName: string, policySetName: string, name: string, policy: Models.Policy, options?: msRest.RequestOptionsBase, callback?: msRest.ServiceCallback<Models.Policy>): Promise<Models.PolicyCreateOrUpdateResourceResponse> {
    return this.client.sendOperationRequest(
      {
        resourceGroupName,
        labName,
        policySetName,
        name,
        policy,
        options
      },
      createOrUpdateResourceOperationSpec,
      callback) as Promise<Models.PolicyCreateOrUpdateResourceResponse>;
  }

  /**
   * Delete policy.
   * @param resourceGroupName The name of the resource group.
   * @param labName The name of the lab.
   * @param policySetName The name of the policy set.
   * @param name The name of the policy.
   * @param [options] The optional parameters
   * @returns Promise<msRest.RestResponse>
   */
  deleteResource(resourceGroupName: string, labName: string, policySetName: string, name: string, options?: msRest.RequestOptionsBase): Promise<msRest.RestResponse>;
  /**
   * @param resourceGroupName The name of the resource group.
   * @param labName The name of the lab.
   * @param policySetName The name of the policy set.
   * @param name The name of the policy.
   * @param callback The callback
   */
  deleteResource(resourceGroupName: string, labName: string, policySetName: string, name: string, callback: msRest.ServiceCallback<void>): void;
  /**
   * @param resourceGroupName The name of the resource group.
   * @param labName The name of the lab.
   * @param policySetName The name of the policy set.
   * @param name The name of the policy.
   * @param options The optional parameters
   * @param callback The callback
   */
  deleteResource(resourceGroupName: string, labName: string, policySetName: string, name: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<void>): void;
  deleteResource(resourceGroupName: string, labName: string, policySetName: string, name: string, options?: msRest.RequestOptionsBase, callback?: msRest.ServiceCallback<void>): Promise<msRest.RestResponse> {
    return this.client.sendOperationRequest(
      {
        resourceGroupName,
        labName,
        policySetName,
        name,
        options
      },
      deleteResourceOperationSpec,
      callback);
  }

  /**
   * Modify properties of policies.
   * @param resourceGroupName The name of the resource group.
   * @param labName The name of the lab.
   * @param policySetName The name of the policy set.
   * @param name The name of the policy.
   * @param policy
   * @param [options] The optional parameters
   * @returns Promise<Models.PolicyPatchResourceResponse>
   */
  patchResource(resourceGroupName: string, labName: string, policySetName: string, name: string, policy: Models.Policy, options?: msRest.RequestOptionsBase): Promise<Models.PolicyPatchResourceResponse>;
  /**
   * @param resourceGroupName The name of the resource group.
   * @param labName The name of the lab.
   * @param policySetName The name of the policy set.
   * @param name The name of the policy.
   * @param policy
   * @param callback The callback
   */
  patchResource(resourceGroupName: string, labName: string, policySetName: string, name: string, policy: Models.Policy, callback: msRest.ServiceCallback<Models.Policy>): void;
  /**
   * @param resourceGroupName The name of the resource group.
   * @param labName The name of the lab.
   * @param policySetName The name of the policy set.
   * @param name The name of the policy.
   * @param policy
   * @param options The optional parameters
   * @param callback The callback
   */
  patchResource(resourceGroupName: string, labName: string, policySetName: string, name: string, policy: Models.Policy, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.Policy>): void;
  patchResource(resourceGroupName: string, labName: string, policySetName: string, name: string, policy: Models.Policy, options?: msRest.RequestOptionsBase, callback?: msRest.ServiceCallback<Models.Policy>): Promise<Models.PolicyPatchResourceResponse> {
    return this.client.sendOperationRequest(
      {
        resourceGroupName,
        labName,
        policySetName,
        name,
        policy,
        options
      },
      patchResourceOperationSpec,
      callback) as Promise<Models.PolicyPatchResourceResponse>;
  }

  /**
   * List policies.
   * @param nextPageLink The NextLink from the previous successful call to List operation.
   * @param [options] The optional parameters
   * @returns Promise<Models.PolicyListNextResponse>
   */
  listNext(nextPageLink: string, options?: msRest.RequestOptionsBase): Promise<Models.PolicyListNextResponse>;
  /**
   * @param nextPageLink The NextLink from the previous successful call to List operation.
   * @param callback The callback
   */
  listNext(nextPageLink: string, callback: msRest.ServiceCallback<Models.ResponseWithContinuationPolicy>): void;
  /**
   * @param nextPageLink The NextLink from the previous successful call to List operation.
   * @param options The optional parameters
   * @param callback The callback
   */
  listNext(nextPageLink: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.ResponseWithContinuationPolicy>): void;
  listNext(nextPageLink: string, options?: msRest.RequestOptionsBase, callback?: msRest.ServiceCallback<Models.ResponseWithContinuationPolicy>): Promise<Models.PolicyListNextResponse> {
    return this.client.sendOperationRequest(
      {
        nextPageLink,
        options
      },
      listNextOperationSpec,
      callback) as Promise<Models.PolicyListNextResponse>;
  }
}

// Operation Specifications
const serializer = new msRest.Serializer(Mappers);
const listOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DevTestLab/labs/{labName}/policysets/{policySetName}/policies",
  urlParameters: [
    Parameters.subscriptionId,
    Parameters.resourceGroupName,
    Parameters.labName,
    Parameters.policySetName
  ],
  queryParameters: [
    Parameters.filter,
    Parameters.top,
    Parameters.orderBy,
    Parameters.apiVersion
  ],
  headerParameters: [
    Parameters.acceptLanguage
  ],
  responses: {
    200: {
      bodyMapper: Mappers.ResponseWithContinuationPolicy
    },
    default: {
      bodyMapper: Mappers.CloudError
    }
  },
  serializer
};

const getResourceOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DevTestLab/labs/{labName}/policysets/{policySetName}/policies/{name}",
  urlParameters: [
    Parameters.subscriptionId,
    Parameters.resourceGroupName,
    Parameters.labName,
    Parameters.policySetName,
    Parameters.name
  ],
  queryParameters: [
    Parameters.apiVersion
  ],
  headerParameters: [
    Parameters.acceptLanguage
  ],
  responses: {
    200: {
      bodyMapper: Mappers.Policy
    },
    default: {
      bodyMapper: Mappers.CloudError
    }
  },
  serializer
};

const createOrUpdateResourceOperationSpec: msRest.OperationSpec = {
  httpMethod: "PUT",
  path: "subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DevTestLab/labs/{labName}/policysets/{policySetName}/policies/{name}",
  urlParameters: [
    Parameters.subscriptionId,
    Parameters.resourceGroupName,
    Parameters.labName,
    Parameters.policySetName,
    Parameters.name
  ],
  queryParameters: [
    Parameters.apiVersion
  ],
  headerParameters: [
    Parameters.acceptLanguage
  ],
  requestBody: {
    parameterPath: "policy",
    mapper: {
      ...Mappers.Policy,
      required: true
    }
  },
  responses: {
    200: {
      bodyMapper: Mappers.Policy
    },
    201: {
      bodyMapper: Mappers.Policy
    },
    default: {
      bodyMapper: Mappers.CloudError
    }
  },
  serializer
};

const deleteResourceOperationSpec: msRest.OperationSpec = {
  httpMethod: "DELETE",
  path: "subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DevTestLab/labs/{labName}/policysets/{policySetName}/policies/{name}",
  urlParameters: [
    Parameters.subscriptionId,
    Parameters.resourceGroupName,
    Parameters.labName,
    Parameters.policySetName,
    Parameters.name
  ],
  queryParameters: [
    Parameters.apiVersion
  ],
  headerParameters: [
    Parameters.acceptLanguage
  ],
  responses: {
    200: {},
    204: {},
    default: {
      bodyMapper: Mappers.CloudError
    }
  },
  serializer
};

const patchResourceOperationSpec: msRest.OperationSpec = {
  httpMethod: "PATCH",
  path: "subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DevTestLab/labs/{labName}/policysets/{policySetName}/policies/{name}",
  urlParameters: [
    Parameters.subscriptionId,
    Parameters.resourceGroupName,
    Parameters.labName,
    Parameters.policySetName,
    Parameters.name
  ],
  queryParameters: [
    Parameters.apiVersion
  ],
  headerParameters: [
    Parameters.acceptLanguage
  ],
  requestBody: {
    parameterPath: "policy",
    mapper: {
      ...Mappers.Policy,
      required: true
    }
  },
  responses: {
    200: {
      bodyMapper: Mappers.Policy
    },
    default: {
      bodyMapper: Mappers.CloudError
    }
  },
  serializer
};

const listNextOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  baseUrl: "https://management.azure.com",
  path: "{nextLink}",
  urlParameters: [
    Parameters.nextPageLink
  ],
  headerParameters: [
    Parameters.acceptLanguage
  ],
  responses: {
    200: {
      bodyMapper: Mappers.ResponseWithContinuationPolicy
    },
    default: {
      bodyMapper: Mappers.CloudError
    }
  },
  serializer
};
