/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import { BaseResource, CloudError, AzureServiceClientOptions } from "ms-rest-azure-js";
import * as msRest from "ms-rest-js";

export { BaseResource, CloudError };


/**
 * @interface
 * An interface representing ActivityParameterValidationSet.
 * Definition of the activity parameter validation set.
 *
 */
export interface ActivityParameterValidationSet {
  /**
   * @member {string} [memberValue] Gets or sets the name of the activity
   * parameter validation set member.
   */
  memberValue?: string;
}

/**
 * @interface
 * An interface representing ActivityParameter.
 * Definition of the activity parameter.
 *
 */
export interface ActivityParameter {
  /**
   * @member {string} [name] Gets or sets the name of the activity parameter.
   */
  name?: string;
  /**
   * @member {string} [type] Gets or sets the type of the activity parameter.
   */
  type?: string;
  /**
   * @member {boolean} [isMandatory] Gets or sets a Boolean value that
   * indicates true if the parameter is required. If the value is false, the
   * parameter is optional.
   */
  isMandatory?: boolean;
  /**
   * @member {boolean} [isDynamic] Gets or sets a Boolean value that indicates
   * true if the parameter is dynamic.
   */
  isDynamic?: boolean;
  /**
   * @member {number} [position] Gets or sets the position of the activity
   * parameter.
   */
  position?: number;
  /**
   * @member {boolean} [valueFromPipeline] Gets or sets a Boolean value that
   * indicates true if the parameter can take values from the incoming pipeline
   * objects. This setting is used if the cmdlet must access the complete input
   * object. false indicates that the parameter cannot take values from the
   * complete input object.
   */
  valueFromPipeline?: boolean;
  /**
   * @member {boolean} [valueFromPipelineByPropertyName] Gets or sets a Boolean
   * value that indicates true if the parameter can be filled from a property
   * of the incoming pipeline object that has the same name as this parameter.
   * false indicates that the parameter cannot be filled from the incoming
   * pipeline object property with the same name.
   */
  valueFromPipelineByPropertyName?: boolean;
  /**
   * @member {boolean} [valueFromRemainingArguments] Gets or sets a Boolean
   * value that indicates true if the cmdlet parameter accepts all the
   * remaining command-line arguments that are associated with this parameter
   * in the form of an array. false if the cmdlet parameter does not accept all
   * the remaining argument values.
   */
  valueFromRemainingArguments?: boolean;
  /**
   * @member {string} [description] Gets or sets the description of the
   * activity parameter.
   */
  description?: string;
  /**
   * @member {ActivityParameterValidationSet[]} [validationSet] Gets or sets
   * the validation set of activity parameter.
   */
  validationSet?: ActivityParameterValidationSet[];
}

/**
 * @interface
 * An interface representing ActivityParameterSet.
 * Definition of the activity parameter set.
 *
 */
export interface ActivityParameterSet {
  /**
   * @member {string} [name] Gets or sets the name of the activity parameter
   * set.
   */
  name?: string;
  /**
   * @member {ActivityParameter[]} [parameters] Gets or sets the parameters of
   * the activity parameter set.
   */
  parameters?: ActivityParameter[];
}

/**
 * @interface
 * An interface representing ActivityOutputType.
 * Definition of the activity output type.
 *
 */
export interface ActivityOutputType {
  /**
   * @member {string} [name] Gets or sets the name of the activity output type.
   */
  name?: string;
  /**
   * @member {string} [type] Gets or sets the type of the activity output type.
   */
  type?: string;
}

/**
 * @interface
 * An interface representing Activity.
 * Definition of the activity.
 *
 */
export interface Activity {
  /**
   * @member {string} [id] Gets or sets the id of the resource.
   */
  id?: string;
  /**
   * @member {string} [name] Gets the name of the activity.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly name?: string;
  /**
   * @member {string} [definition] Gets or sets the user name of the activity.
   */
  definition?: string;
  /**
   * @member {ActivityParameterSet[]} [parameterSets] Gets or sets the
   * parameter sets of the activity.
   */
  parameterSets?: ActivityParameterSet[];
  /**
   * @member {ActivityOutputType[]} [outputTypes] Gets or sets the output types
   * of the activity.
   */
  outputTypes?: ActivityOutputType[];
  /**
   * @member {Date} [creationTime] Gets or sets the creation time.
   */
  creationTime?: Date;
  /**
   * @member {Date} [lastModifiedTime] Gets or sets the last modified time.
   */
  lastModifiedTime?: Date;
  /**
   * @member {string} [description] Gets or sets the description.
   */
  description?: string;
}

/**
 * @interface
 * An interface representing ActivityListResult.
 * The response model for the list activity operation.
 *
 */
export interface ActivityListResult {
  /**
   * @member {Activity[]} [value] Gets or sets a list of activities.
   */
  value?: Activity[];
  /**
   * @member {string} [nextLink] Gets or sets the next link.
   */
  nextLink?: string;
}

/**
 * @interface
 * An interface representing ModuleErrorInfo.
 * Definition of the module error info type.
 *
 */
export interface ModuleErrorInfo {
  /**
   * @member {string} [code] Gets or sets the error code.
   */
  code?: string;
  /**
   * @member {string} [message] Gets or sets the error message.
   */
  message?: string;
}

/**
 * @interface
 * An interface representing ContentHash.
 * Definition of the runbook property type.
 *
 */
export interface ContentHash {
  /**
   * @member {string} algorithm Gets or sets the content hash algorithm used to
   * hash the content.
   */
  algorithm: string;
  /**
   * @member {string} value Gets or sets expected hash value of the content.
   */
  value: string;
}

/**
 * @interface
 * An interface representing ContentLink.
 * Definition of the content link.
 *
 */
export interface ContentLink {
  /**
   * @member {string} [uri] Gets or sets the uri of the runbook content.
   */
  uri?: string;
  /**
   * @member {ContentHash} [contentHash] Gets or sets the hash.
   */
  contentHash?: ContentHash;
  /**
   * @member {string} [version] Gets or sets the version of the content.
   */
  version?: string;
}

/**
 * @interface
 * An interface representing Resource.
 * The core properties of ARM resources
 *
 * @extends BaseResource
 */
export interface Resource extends BaseResource {
  /**
   * @member {string} [id] Fully qualified resource Id for the resource
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly id?: string;
  /**
   * @member {string} [name] The name of the resource
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly name?: string;
  /**
   * @member {string} [type] The type of the resource.
   * **NOTE: This property will not be serialized. It can only be populated by
   * the server.**
   */
  readonly type?: string;
}

/**
 * @interface
 * An interface representing TrackedResource.
 * The resource model definition for a ARM tracked top level resource
 *
 * @extends Resource
 */
export interface TrackedResource extends Resource {
  /**
   * @member {{ [propertyName: string]: string }} [tags] Resource tags.
   */
  tags?: { [propertyName: string]: string };
  /**
   * @member {string} [location] The Azure Region where the resource lives
   */
  location?: string;
}

/**
 * @interface
 * An interface representing Module.
 * Definition of the module type.
 *
 * @extends TrackedResource
 */
export interface Module extends TrackedResource {
  /**
   * @member {boolean} [isGlobal] Gets or sets the isGlobal flag of the module.
   */
  isGlobal?: boolean;
  /**
   * @member {string} [version] Gets or sets the version of the module.
   */
  version?: string;
  /**
   * @member {number} [sizeInBytes] Gets or sets the size in bytes of the
   * module.
   */
  sizeInBytes?: number;
  /**
   * @member {number} [activityCount] Gets or sets the activity count of the
   * module.
   */
  activityCount?: number;
  /**
   * @member {ModuleProvisioningState} [provisioningState] Gets or sets the
   * provisioning state of the module. Possible values include: 'Created',
   * 'Creating', 'StartingImportModuleRunbook', 'RunningImportModuleRunbook',
   * 'ContentRetrieved', 'ContentDownloaded', 'ContentValidated',
   * 'ConnectionTypeImported', 'ContentStored', 'ModuleDataStored',
   * 'ActivitiesStored', 'ModuleImportRunbookComplete', 'Succeeded', 'Failed',
   * 'Cancelled', 'Updating'
   */
  provisioningState?: ModuleProvisioningState;
  /**
   * @member {ContentLink} [contentLink] Gets or sets the contentLink of the
   * module.
   */
  contentLink?: ContentLink;
  /**
   * @member {ModuleErrorInfo} [error] Gets or sets the error info of the
   * module.
   */
  error?: ModuleErrorInfo;
  /**
   * @member {Date} [creationTime] Gets or sets the creation time.
   */
  creationTime?: Date;
  /**
   * @member {Date} [lastModifiedTime] Gets or sets the last modified time.
   */
  lastModifiedTime?: Date;
  /**
   * @member {string} [description] Gets or sets the description.
   */
  description?: string;
  /**
   * @member {boolean} [isComposite] Gets or sets type of module, if its
   * composite or not.
   */
  isComposite?: boolean;
  /**
   * @member {string} [etag] Gets or sets the etag of the resource.
   */
  etag?: string;
}

/**
 * @interface
 * An interface representing PythonPackageCreateParameters.
 * The parameters supplied to the create or update module operation.
 *
 */
export interface PythonPackageCreateParameters {
  /**
   * @member {ContentLink} contentLink Gets or sets the module content link.
   */
  contentLink: ContentLink;
  /**
   * @member {{ [propertyName: string]: string }} [tags] Gets or sets the tags
   * attached to the resource.
   */
  tags?: { [propertyName: string]: string };
}

/**
 * @interface
 * An interface representing PythonPackageUpdateParameters.
 * The parameters supplied to the update module operation.
 *
 */
export interface PythonPackageUpdateParameters {
  /**
   * @member {{ [propertyName: string]: string }} [tags] Gets or sets the tags
   * attached to the resource.
   */
  tags?: { [propertyName: string]: string };
}

/**
 * @interface
 * An interface representing TypeField.
 * Information about a field of a type.
 *
 */
export interface TypeField {
  /**
   * @member {string} [name] Gets or sets the name of the field.
   */
  name?: string;
  /**
   * @member {string} [type] Gets or sets the type of the field.
   */
  type?: string;
}

/**
 * @interface
 * An interface representing TypeFieldListResult.
 * The response model for the list fields operation.
 *
 */
export interface TypeFieldListResult {
  /**
   * @member {TypeField[]} [value] Gets or sets a list of fields.
   */
  value?: TypeField[];
}

/**
 * @interface
 * An interface representing ProxyResource.
 * ARM proxy resource.
 *
 * @extends Resource
 */
export interface ProxyResource extends Resource {
}

/**
 * @interface
 * An interface representing ErrorResponse.
 * Error response of an operation failure
 *
 */
export interface ErrorResponse {
  /**
   * @member {string} [code] Error code
   */
  code?: string;
  /**
   * @member {string} [message] Error message indicating why the operation
   * failed.
   */
  message?: string;
}

/**
 * @interface
 * An interface representing JobStream.
 * Definition of the job stream.
 *
 */
export interface JobStream {
  /**
   * @member {string} [id] Gets or sets the id of the resource.
   */
  id?: string;
  /**
   * @member {string} [jobStreamId] Gets or sets the id of the job stream.
   */
  jobStreamId?: string;
  /**
   * @member {Date} [time] Gets or sets the creation time of the job.
   */
  time?: Date;
  /**
   * @member {JobStreamType} [streamType] Gets or sets the stream type.
   * Possible values include: 'Progress', 'Output', 'Warning', 'Error',
   * 'Debug', 'Verbose', 'Any'
   */
  streamType?: JobStreamType;
  /**
   * @member {string} [streamText] Gets or sets the stream text.
   */
  streamText?: string;
  /**
   * @member {string} [summary] Gets or sets the summary.
   */
  summary?: string;
  /**
   * @member {{ [propertyName: string]: any }} [value] Gets or sets the values
   * of the job stream.
   */
  value?: { [propertyName: string]: any };
}

/**
 * @interface
 * An interface representing RunbookParameter.
 * Definition of the runbook parameter type.
 *
 */
export interface RunbookParameter {
  /**
   * @member {string} [type] Gets or sets the type of the parameter.
   */
  type?: string;
  /**
   * @member {boolean} [isMandatory] Gets or sets a Boolean value to indicate
   * whether the parameter is madatory or not.
   */
  isMandatory?: boolean;
  /**
   * @member {number} [position] Get or sets the position of the parameter.
   */
  position?: number;
  /**
   * @member {string} [defaultValue] Gets or sets the default value of
   * parameter.
   */
  defaultValue?: string;
}

/**
 * @interface
 * An interface representing RunbookDraft.
 */
export interface RunbookDraft {
  /**
   * @member {boolean} [inEdit] Gets or sets whether runbook is in edit mode.
   */
  inEdit?: boolean;
  /**
   * @member {ContentLink} [draftContentLink] Gets or sets the draft runbook
   * content link.
   */
  draftContentLink?: ContentLink;
  /**
   * @member {Date} [creationTime] Gets or sets the creation time of the
   * runbook draft.
   */
  creationTime?: Date;
  /**
   * @member {Date} [lastModifiedTime] Gets or sets the last modified time of
   * the runbook draft.
   */
  lastModifiedTime?: Date;
  /**
   * @member {{ [propertyName: string]: RunbookParameter }} [parameters] Gets
   * or sets the runbook draft parameters.
   */
  parameters?: { [propertyName: string]: RunbookParameter };
  /**
   * @member {string[]} [outputTypes] Gets or sets the runbook output types.
   */
  outputTypes?: string[];
}

/**
 * @interface
 * An interface representing Runbook.
 * Definition of the runbook type.
 *
 * @extends TrackedResource
 */
export interface Runbook extends TrackedResource {
  /**
   * @member {RunbookTypeEnum} [runbookType] Gets or sets the type of the
   * runbook. Possible values include: 'Script', 'Graph', 'PowerShellWorkflow',
   * 'PowerShell', 'GraphPowerShellWorkflow', 'GraphPowerShell'
   */
  runbookType?: RunbookTypeEnum;
  /**
   * @member {ContentLink} [publishContentLink] Gets or sets the published
   * runbook content link.
   */
  publishContentLink?: ContentLink;
  /**
   * @member {RunbookState} [state] Gets or sets the state of the runbook.
   * Possible values include: 'New', 'Edit', 'Published'
   */
  state?: RunbookState;
  /**
   * @member {boolean} [logVerbose] Gets or sets verbose log option.
   */
  logVerbose?: boolean;
  /**
   * @member {boolean} [logProgress] Gets or sets progress log option.
   */
  logProgress?: boolean;
  /**
   * @member {number} [logActivityTrace] Gets or sets the option to log
   * activity trace of the runbook.
   */
  logActivityTrace?: number;
  /**
   * @member {number} [jobCount] Gets or sets the job count of the runbook.
   */
  jobCount?: number;
  /**
   * @member {{ [propertyName: string]: RunbookParameter }} [parameters] Gets
   * or sets the runbook parameters.
   */
  parameters?: { [propertyName: string]: RunbookParameter };
  /**
   * @member {string[]} [outputTypes] Gets or sets the runbook output types.
   */
  outputTypes?: string[];
  /**
   * @member {RunbookDraft} [draft] Gets or sets the draft runbook properties.
   */
  draft?: RunbookDraft;
  /**
   * @member {RunbookProvisioningState} [provisioningState] Gets or sets the
   * provisioning state of the runbook. Possible values include: 'Succeeded'
   */
  provisioningState?: RunbookProvisioningState;
  /**
   * @member {string} [lastModifiedBy] Gets or sets the last modified by.
   */
  lastModifiedBy?: string;
  /**
   * @member {Date} [creationTime] Gets or sets the creation time.
   */
  creationTime?: Date;
  /**
   * @member {Date} [lastModifiedTime] Gets or sets the last modified time.
   */
  lastModifiedTime?: Date;
  /**
   * @member {string} [description] Gets or sets the description.
   */
  description?: string;
  /**
   * @member {string} [etag] Gets or sets the etag of the resource.
   */
  etag?: string;
}

/**
 * @interface
 * An interface representing RunbookCreateOrUpdateParameters.
 * The parameters supplied to the create or update runbook operation.
 *
 */
export interface RunbookCreateOrUpdateParameters {
  /**
   * @member {boolean} [logVerbose] Gets or sets verbose log option.
   */
  logVerbose?: boolean;
  /**
   * @member {boolean} [logProgress] Gets or sets progress log option.
   */
  logProgress?: boolean;
  /**
   * @member {RunbookTypeEnum} runbookType Gets or sets the type of the
   * runbook. Possible values include: 'Script', 'Graph', 'PowerShellWorkflow',
   * 'PowerShell', 'GraphPowerShellWorkflow', 'GraphPowerShell'
   */
  runbookType: RunbookTypeEnum;
  /**
   * @member {RunbookDraft} [draft] Gets or sets the draft runbook properties.
   */
  draft?: RunbookDraft;
  /**
   * @member {ContentLink} [publishContentLink] Gets or sets the published
   * runbook content link.
   */
  publishContentLink?: ContentLink;
  /**
   * @member {string} [description] Gets or sets the description of the
   * runbook.
   */
  description?: string;
  /**
   * @member {number} [logActivityTrace] Gets or sets the activity-level
   * tracing options of the runbook.
   */
  logActivityTrace?: number;
  /**
   * @member {string} [name] Gets or sets the name of the resource.
   */
  name?: string;
  /**
   * @member {string} [location] Gets or sets the location of the resource.
   */
  location?: string;
  /**
   * @member {{ [propertyName: string]: string }} [tags] Gets or sets the tags
   * attached to the resource.
   */
  tags?: { [propertyName: string]: string };
}

/**
 * @interface
 * An interface representing RunbookUpdateParameters.
 * The parameters supplied to the update runbook operation.
 *
 */
export interface RunbookUpdateParameters {
  /**
   * @member {string} [description] Gets or sets the description of the
   * runbook.
   */
  description?: string;
  /**
   * @member {boolean} [logVerbose] Gets or sets verbose log option.
   */
  logVerbose?: boolean;
  /**
   * @member {boolean} [logProgress] Gets or sets progress log option.
   */
  logProgress?: boolean;
  /**
   * @member {number} [logActivityTrace] Gets or sets the activity-level
   * tracing options of the runbook.
   */
  logActivityTrace?: number;
  /**
   * @member {string} [name] Gets or sets the name of the resource.
   */
  name?: string;
  /**
   * @member {string} [location] Gets or sets the location of the resource.
   */
  location?: string;
  /**
   * @member {{ [propertyName: string]: string }} [tags] Gets or sets the tags
   * attached to the resource.
   */
  tags?: { [propertyName: string]: string };
}

/**
 * @interface
 * An interface representing RunbookDraftUndoEditResult.
 * The response model for the undoedit runbook operation.
 *
 */
export interface RunbookDraftUndoEditResult {
  /**
   * @member {HttpStatusCode} [statusCode] Possible values include: 'Continue',
   * 'SwitchingProtocols', 'OK', 'Created', 'Accepted',
   * 'NonAuthoritativeInformation', 'NoContent', 'ResetContent',
   * 'PartialContent', 'MultipleChoices', 'Ambiguous', 'MovedPermanently',
   * 'Moved', 'Found', 'Redirect', 'SeeOther', 'RedirectMethod', 'NotModified',
   * 'UseProxy', 'Unused', 'TemporaryRedirect', 'RedirectKeepVerb',
   * 'BadRequest', 'Unauthorized', 'PaymentRequired', 'Forbidden', 'NotFound',
   * 'MethodNotAllowed', 'NotAcceptable', 'ProxyAuthenticationRequired',
   * 'RequestTimeout', 'Conflict', 'Gone', 'LengthRequired',
   * 'PreconditionFailed', 'RequestEntityTooLarge', 'RequestUriTooLong',
   * 'UnsupportedMediaType', 'RequestedRangeNotSatisfiable',
   * 'ExpectationFailed', 'UpgradeRequired', 'InternalServerError',
   * 'NotImplemented', 'BadGateway', 'ServiceUnavailable', 'GatewayTimeout',
   * 'HttpVersionNotSupported'
   */
  statusCode?: HttpStatusCode;
  /**
   * @member {string} [requestId]
   */
  requestId?: string;
}

/**
 * @interface
 * An interface representing TestJobCreateParameters.
 * The parameters supplied to the create test job operation.
 *
 */
export interface TestJobCreateParameters {
  /**
   * @member {{ [propertyName: string]: string }} [parameters] Gets or sets the
   * parameters of the test job.
   */
  parameters?: { [propertyName: string]: string };
  /**
   * @member {string} [runOn] Gets or sets the runOn which specifies the group
   * name where the job is to be executed.
   */
  runOn?: string;
}

/**
 * @interface
 * An interface representing TestJob.
 * Definition of the test job.
 *
 */
export interface TestJob {
  /**
   * @member {Date} [creationTime] Gets or sets the creation time of the test
   * job.
   */
  creationTime?: Date;
  /**
   * @member {string} [status] Gets or sets the status of the test job.
   */
  status?: string;
  /**
   * @member {string} [statusDetails] Gets or sets the status details of the
   * test job.
   */
  statusDetails?: string;
  /**
   * @member {string} [runOn] Gets or sets the runOn which specifies the group
   * name where the job is to be executed.
   */
  runOn?: string;
  /**
   * @member {Date} [startTime] Gets or sets the start time of the test job.
   */
  startTime?: Date;
  /**
   * @member {Date} [endTime] Gets or sets the end time of the test job.
   */
  endTime?: Date;
  /**
   * @member {string} [exception] Gets or sets the exception of the test job.
   */
  exception?: string;
  /**
   * @member {Date} [lastModifiedTime] Gets or sets the last modified time of
   * the test job.
   */
  lastModifiedTime?: Date;
  /**
   * @member {Date} [lastStatusModifiedTime] Gets or sets the last status
   * modified time of the test job.
   */
  lastStatusModifiedTime?: Date;
  /**
   * @member {{ [propertyName: string]: string }} [parameters] Gets or sets the
   * parameters of the test job.
   */
  parameters?: { [propertyName: string]: string };
  /**
   * @member {number} [logActivityTrace] The activity-level tracing options of
   * the runbook.
   */
  logActivityTrace?: number;
}

/**
 * @interface
 * An interface representing RunbookCreateOrUpdateDraftProperties.
 * The parameters supplied to the create or update dratft runbook properties.
 *
 */
export interface RunbookCreateOrUpdateDraftProperties {
  /**
   * @member {boolean} [logVerbose] Gets or sets verbose log option.
   */
  logVerbose?: boolean;
  /**
   * @member {boolean} [logProgress] Gets or sets progress log option.
   */
  logProgress?: boolean;
  /**
   * @member {RunbookTypeEnum} runbookType Gets or sets the type of the
   * runbook. Possible values include: 'Script', 'Graph', 'PowerShellWorkflow',
   * 'PowerShell', 'GraphPowerShellWorkflow', 'GraphPowerShell'
   */
  runbookType: RunbookTypeEnum;
  /**
   * @member {RunbookDraft} draft Gets or sets the draft runbook properties.
   */
  draft: RunbookDraft;
  /**
   * @member {string} [description] Gets or sets the description of the
   * runbook.
   */
  description?: string;
  /**
   * @member {number} [logActivityTrace] Gets or sets the activity-level
   * tracing options of the runbook.
   */
  logActivityTrace?: number;
}

/**
 * @interface
 * An interface representing RunbookCreateOrUpdateDraftParameters.
 * The parameters supplied to the create or update runbook operation.
 *
 */
export interface RunbookCreateOrUpdateDraftParameters {
  /**
   * @member {string} runbookContent Content of the Runbook.
   */
  runbookContent: string;
}

/**
 * @interface
 * An interface representing TestJobStreamsListByTestJobOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface TestJobStreamsListByTestJobOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {string} [filter] The filter to apply on the operation.
   */
  filter?: string;
}

/**
 * @interface
 * An interface representing AutomationClientOptions.
 * @extends AzureServiceClientOptions
 */
export interface AutomationClientOptions extends AzureServiceClientOptions {
  /**
   * @member {string} [baseUri]
   */
  baseUri?: string;
}

/**
 * @interface
 * An interface representing RunbookDraftReplaceContentHeaders.
 * Defines headers for ReplaceContent operation.
 *
 */
export interface RunbookDraftReplaceContentHeaders {
  /**
   * @member {string} [location] URL to query for status of the operation.
   */
  location: string;
}

/**
 * @interface
 * An interface representing RunbookPublishHeaders.
 * Defines headers for Publish operation.
 *
 */
export interface RunbookPublishHeaders {
  /**
   * @member {string} [location] URL to query for status of the operation.
   */
  location: string;
}


/**
 * @interface
 * An interface representing the ModuleListResult.
 * The response model for the list module operation.
 *
 * @extends Array<Module>
 */
export interface ModuleListResult extends Array<Module> {
  /**
   * @member {string} [nextLink] Gets or sets the next link.
   */
  nextLink?: string;
}

/**
 * @interface
 * An interface representing the RunbookListResult.
 * The response model for the list runbook operation.
 *
 * @extends Array<Runbook>
 */
export interface RunbookListResult extends Array<Runbook> {
  /**
   * @member {string} [nextLink] Gets or sets the next link.
   */
  nextLink?: string;
}

/**
 * @interface
 * An interface representing the JobStreamListResult.
 * The response model for the list job stream operation.
 *
 * @extends Array<JobStream>
 */
export interface JobStreamListResult extends Array<JobStream> {
  /**
   * @member {string} [nextLink] Gets or sets the next link.
   */
  nextLink?: string;
}

/**
 * Defines values for ModuleProvisioningState.
 * Possible values include: 'Created', 'Creating', 'StartingImportModuleRunbook',
 * 'RunningImportModuleRunbook', 'ContentRetrieved', 'ContentDownloaded', 'ContentValidated',
 * 'ConnectionTypeImported', 'ContentStored', 'ModuleDataStored', 'ActivitiesStored',
 * 'ModuleImportRunbookComplete', 'Succeeded', 'Failed', 'Cancelled', 'Updating'
 * @readonly
 * @enum {string}
 */
export type ModuleProvisioningState = 'Created' | 'Creating' | 'StartingImportModuleRunbook' | 'RunningImportModuleRunbook' | 'ContentRetrieved' | 'ContentDownloaded' | 'ContentValidated' | 'ConnectionTypeImported' | 'ContentStored' | 'ModuleDataStored' | 'ActivitiesStored' | 'ModuleImportRunbookComplete' | 'Succeeded' | 'Failed' | 'Cancelled' | 'Updating';

/**
 * Defines values for JobStreamType.
 * Possible values include: 'Progress', 'Output', 'Warning', 'Error', 'Debug', 'Verbose', 'Any'
 * @readonly
 * @enum {string}
 */
export type JobStreamType = 'Progress' | 'Output' | 'Warning' | 'Error' | 'Debug' | 'Verbose' | 'Any';

/**
 * Defines values for RunbookTypeEnum.
 * Possible values include: 'Script', 'Graph', 'PowerShellWorkflow', 'PowerShell',
 * 'GraphPowerShellWorkflow', 'GraphPowerShell'
 * @readonly
 * @enum {string}
 */
export type RunbookTypeEnum = 'Script' | 'Graph' | 'PowerShellWorkflow' | 'PowerShell' | 'GraphPowerShellWorkflow' | 'GraphPowerShell';

/**
 * Defines values for RunbookState.
 * Possible values include: 'New', 'Edit', 'Published'
 * @readonly
 * @enum {string}
 */
export type RunbookState = 'New' | 'Edit' | 'Published';

/**
 * Defines values for RunbookProvisioningState.
 * Possible values include: 'Succeeded'
 * @readonly
 * @enum {string}
 */
export type RunbookProvisioningState = 'Succeeded';

/**
 * Defines values for HttpStatusCode.
 * Possible values include: 'Continue', 'SwitchingProtocols', 'OK', 'Created', 'Accepted',
 * 'NonAuthoritativeInformation', 'NoContent', 'ResetContent', 'PartialContent', 'MultipleChoices',
 * 'Ambiguous', 'MovedPermanently', 'Moved', 'Found', 'Redirect', 'SeeOther', 'RedirectMethod',
 * 'NotModified', 'UseProxy', 'Unused', 'TemporaryRedirect', 'RedirectKeepVerb', 'BadRequest',
 * 'Unauthorized', 'PaymentRequired', 'Forbidden', 'NotFound', 'MethodNotAllowed', 'NotAcceptable',
 * 'ProxyAuthenticationRequired', 'RequestTimeout', 'Conflict', 'Gone', 'LengthRequired',
 * 'PreconditionFailed', 'RequestEntityTooLarge', 'RequestUriTooLong', 'UnsupportedMediaType',
 * 'RequestedRangeNotSatisfiable', 'ExpectationFailed', 'UpgradeRequired', 'InternalServerError',
 * 'NotImplemented', 'BadGateway', 'ServiceUnavailable', 'GatewayTimeout',
 * 'HttpVersionNotSupported'
 * @readonly
 * @enum {string}
 */
export type HttpStatusCode = 'Continue' | 'SwitchingProtocols' | 'OK' | 'Created' | 'Accepted' | 'NonAuthoritativeInformation' | 'NoContent' | 'ResetContent' | 'PartialContent' | 'MultipleChoices' | 'Ambiguous' | 'MovedPermanently' | 'Moved' | 'Found' | 'Redirect' | 'SeeOther' | 'RedirectMethod' | 'NotModified' | 'UseProxy' | 'Unused' | 'TemporaryRedirect' | 'RedirectKeepVerb' | 'BadRequest' | 'Unauthorized' | 'PaymentRequired' | 'Forbidden' | 'NotFound' | 'MethodNotAllowed' | 'NotAcceptable' | 'ProxyAuthenticationRequired' | 'RequestTimeout' | 'Conflict' | 'Gone' | 'LengthRequired' | 'PreconditionFailed' | 'RequestEntityTooLarge' | 'RequestUriTooLong' | 'UnsupportedMediaType' | 'RequestedRangeNotSatisfiable' | 'ExpectationFailed' | 'UpgradeRequired' | 'InternalServerError' | 'NotImplemented' | 'BadGateway' | 'ServiceUnavailable' | 'GatewayTimeout' | 'HttpVersionNotSupported';

/**
 * Contains response data for the get operation.
 */
export type Python2PackageGetResponse = Module & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: Module;
    };
};

/**
 * Contains response data for the createOrUpdate operation.
 */
export type Python2PackageCreateOrUpdateResponse = Module & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: Module;
    };
};

/**
 * Contains response data for the update operation.
 */
export type Python2PackageUpdateResponse = Module & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: Module;
    };
};

/**
 * Contains response data for the listByAutomationAccount operation.
 */
export type Python2PackageListByAutomationAccountResponse = ModuleListResult & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: ModuleListResult;
    };
};

/**
 * Contains response data for the listByAutomationAccountNext operation.
 */
export type Python2PackageListByAutomationAccountNextResponse = ModuleListResult & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: ModuleListResult;
    };
};

/**
 * Contains response data for the getContent operation.
 */
export type RunbookDraftGetContentResponse = {
  /**
   * BROWSER ONLY
   *
   * The response body as a browser Blob.
   * Always undefined in node.js.
   */
  blobBody?: Promise<Blob>;
  /**
   * NODEJS ONLY
   *
   * The response body as a node.js Readable stream.
   * Always undefined in the browser.
   */
  readableStreamBody?: NodeJS.ReadableStream;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse;
};

/**
 * Contains response data for the replaceContent operation.
 */
export type RunbookDraftReplaceContentResponse = RunbookDraftReplaceContentHeaders & {
  /**
   * BROWSER ONLY
   *
   * The response body as a browser Blob.
   * Always undefined in node.js.
   */
  blobBody?: Promise<Blob>;
  /**
   * NODEJS ONLY
   *
   * The response body as a node.js Readable stream.
   * Always undefined in the browser.
   */
  readableStreamBody?: NodeJS.ReadableStream;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The parsed HTTP response headers.
       */
      parsedHeaders: RunbookDraftReplaceContentHeaders;
    };
};

/**
 * Contains response data for the get operation.
 */
export type RunbookDraftGetResponse = RunbookDraft & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: RunbookDraft;
    };
};

/**
 * Contains response data for the undoEdit operation.
 */
export type RunbookDraftUndoEditResponse = RunbookDraftUndoEditResult & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: RunbookDraftUndoEditResult;
    };
};

/**
 * Contains response data for the publish operation.
 */
export type RunbookPublishResponse = RunbookPublishHeaders & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The parsed HTTP response headers.
       */
      parsedHeaders: RunbookPublishHeaders;
    };
};

/**
 * Contains response data for the getContent operation.
 */
export type RunbookGetContentResponse = {
  /**
   * BROWSER ONLY
   *
   * The response body as a browser Blob.
   * Always undefined in node.js.
   */
  blobBody?: Promise<Blob>;
  /**
   * NODEJS ONLY
   *
   * The response body as a node.js Readable stream.
   * Always undefined in the browser.
   */
  readableStreamBody?: NodeJS.ReadableStream;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse;
};

/**
 * Contains response data for the get operation.
 */
export type RunbookGetResponse = Runbook & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: Runbook;
    };
};

/**
 * Contains response data for the createOrUpdate operation.
 */
export type RunbookCreateOrUpdateResponse = Runbook & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: Runbook;
    };
};

/**
 * Contains response data for the update operation.
 */
export type RunbookUpdateResponse = Runbook & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: Runbook;
    };
};

/**
 * Contains response data for the listByAutomationAccount operation.
 */
export type RunbookListByAutomationAccountResponse = RunbookListResult & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: RunbookListResult;
    };
};

/**
 * Contains response data for the listByAutomationAccountNext operation.
 */
export type RunbookListByAutomationAccountNextResponse = RunbookListResult & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: RunbookListResult;
    };
};

/**
 * Contains response data for the get operation.
 */
export type TestJobStreamsGetResponse = JobStream & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: JobStream;
    };
};

/**
 * Contains response data for the listByTestJob operation.
 */
export type TestJobStreamsListByTestJobResponse = JobStreamListResult & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: JobStreamListResult;
    };
};

/**
 * Contains response data for the listByTestJobNext operation.
 */
export type TestJobStreamsListByTestJobNextResponse = JobStreamListResult & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: JobStreamListResult;
    };
};

/**
 * Contains response data for the create operation.
 */
export type TestJobCreateResponse = TestJob & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: TestJob;
    };
};

/**
 * Contains response data for the get operation.
 */
export type TestJobGetResponse = TestJob & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: TestJob;
    };
};
