/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import { CloudErrorMapper, BaseResourceMapper } from "ms-rest-azure-js";
import * as msRest from "ms-rest-js";

export const CloudError = CloudErrorMapper;
export const BaseResource = BaseResourceMapper;

export const ActivityParameterValidationSet: msRest.CompositeMapper = {
  serializedName: "ActivityParameterValidationSet",
  type: {
    name: "Composite",
    className: "ActivityParameterValidationSet",
    modelProperties: {
      memberValue: {
        serializedName: "memberValue",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const ActivityParameter: msRest.CompositeMapper = {
  serializedName: "ActivityParameter",
  type: {
    name: "Composite",
    className: "ActivityParameter",
    modelProperties: {
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      type: {
        serializedName: "type",
        type: {
          name: "String"
        }
      },
      isMandatory: {
        serializedName: "isMandatory",
        type: {
          name: "Boolean"
        }
      },
      isDynamic: {
        serializedName: "isDynamic",
        type: {
          name: "Boolean"
        }
      },
      position: {
        serializedName: "position",
        type: {
          name: "Number"
        }
      },
      valueFromPipeline: {
        serializedName: "valueFromPipeline",
        type: {
          name: "Boolean"
        }
      },
      valueFromPipelineByPropertyName: {
        serializedName: "valueFromPipelineByPropertyName",
        type: {
          name: "Boolean"
        }
      },
      valueFromRemainingArguments: {
        serializedName: "valueFromRemainingArguments",
        type: {
          name: "Boolean"
        }
      },
      description: {
        serializedName: "description",
        type: {
          name: "String"
        }
      },
      validationSet: {
        serializedName: "validationSet",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "ActivityParameterValidationSet"
            }
          }
        }
      }
    }
  }
};

export const ActivityParameterSet: msRest.CompositeMapper = {
  serializedName: "ActivityParameterSet",
  type: {
    name: "Composite",
    className: "ActivityParameterSet",
    modelProperties: {
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      parameters: {
        serializedName: "parameters",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "ActivityParameter"
            }
          }
        }
      }
    }
  }
};

export const ActivityOutputType: msRest.CompositeMapper = {
  serializedName: "ActivityOutputType",
  type: {
    name: "Composite",
    className: "ActivityOutputType",
    modelProperties: {
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      type: {
        serializedName: "type",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const Activity: msRest.CompositeMapper = {
  serializedName: "Activity",
  type: {
    name: "Composite",
    className: "Activity",
    modelProperties: {
      id: {
        serializedName: "id",
        type: {
          name: "String"
        }
      },
      name: {
        readOnly: true,
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      definition: {
        serializedName: "properties.definition",
        type: {
          name: "String"
        }
      },
      parameterSets: {
        serializedName: "properties.parameterSets",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "ActivityParameterSet"
            }
          }
        }
      },
      outputTypes: {
        serializedName: "properties.outputTypes",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "ActivityOutputType"
            }
          }
        }
      },
      creationTime: {
        nullable: false,
        serializedName: "properties.creationTime",
        type: {
          name: "DateTime"
        }
      },
      lastModifiedTime: {
        nullable: false,
        serializedName: "properties.lastModifiedTime",
        type: {
          name: "DateTime"
        }
      },
      description: {
        serializedName: "properties.description",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const ActivityListResult: msRest.CompositeMapper = {
  serializedName: "ActivityListResult",
  type: {
    name: "Composite",
    className: "ActivityListResult",
    modelProperties: {
      value: {
        serializedName: "value",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "Activity"
            }
          }
        }
      },
      nextLink: {
        serializedName: "nextLink",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const ModuleErrorInfo: msRest.CompositeMapper = {
  serializedName: "ModuleErrorInfo",
  type: {
    name: "Composite",
    className: "ModuleErrorInfo",
    modelProperties: {
      code: {
        serializedName: "code",
        type: {
          name: "String"
        }
      },
      message: {
        serializedName: "message",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const ContentHash: msRest.CompositeMapper = {
  serializedName: "ContentHash",
  type: {
    name: "Composite",
    className: "ContentHash",
    modelProperties: {
      algorithm: {
        required: true,
        serializedName: "algorithm",
        type: {
          name: "String"
        }
      },
      value: {
        required: true,
        serializedName: "value",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const ContentLink: msRest.CompositeMapper = {
  serializedName: "ContentLink",
  type: {
    name: "Composite",
    className: "ContentLink",
    modelProperties: {
      uri: {
        serializedName: "uri",
        type: {
          name: "String"
        }
      },
      contentHash: {
        serializedName: "contentHash",
        type: {
          name: "Composite",
          className: "ContentHash"
        }
      },
      version: {
        serializedName: "version",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const Resource: msRest.CompositeMapper = {
  serializedName: "Resource",
  type: {
    name: "Composite",
    className: "Resource",
    modelProperties: {
      id: {
        readOnly: true,
        serializedName: "id",
        type: {
          name: "String"
        }
      },
      name: {
        readOnly: true,
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      type: {
        readOnly: true,
        serializedName: "type",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const TrackedResource: msRest.CompositeMapper = {
  serializedName: "TrackedResource",
  type: {
    name: "Composite",
    className: "TrackedResource",
    modelProperties: {
      ...Resource.type.modelProperties,
      tags: {
        serializedName: "tags",
        type: {
          name: "Dictionary",
          value: {
            type: {
              name: "String"
            }
          }
        }
      },
      location: {
        serializedName: "location",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const Module: msRest.CompositeMapper = {
  serializedName: "Module",
  type: {
    name: "Composite",
    className: "Module",
    modelProperties: {
      ...TrackedResource.type.modelProperties,
      isGlobal: {
        serializedName: "properties.isGlobal",
        type: {
          name: "Boolean"
        }
      },
      version: {
        serializedName: "properties.version",
        type: {
          name: "String"
        }
      },
      sizeInBytes: {
        serializedName: "properties.sizeInBytes",
        type: {
          name: "Number"
        }
      },
      activityCount: {
        serializedName: "properties.activityCount",
        type: {
          name: "Number"
        }
      },
      provisioningState: {
        serializedName: "properties.provisioningState",
        type: {
          name: "Enum",
          allowedValues: [
            "Created",
            "Creating",
            "StartingImportModuleRunbook",
            "RunningImportModuleRunbook",
            "ContentRetrieved",
            "ContentDownloaded",
            "ContentValidated",
            "ConnectionTypeImported",
            "ContentStored",
            "ModuleDataStored",
            "ActivitiesStored",
            "ModuleImportRunbookComplete",
            "Succeeded",
            "Failed",
            "Cancelled",
            "Updating"
          ]
        }
      },
      contentLink: {
        serializedName: "properties.contentLink",
        type: {
          name: "Composite",
          className: "ContentLink"
        }
      },
      error: {
        serializedName: "properties.error",
        type: {
          name: "Composite",
          className: "ModuleErrorInfo"
        }
      },
      creationTime: {
        nullable: false,
        serializedName: "properties.creationTime",
        type: {
          name: "DateTime"
        }
      },
      lastModifiedTime: {
        nullable: false,
        serializedName: "properties.lastModifiedTime",
        type: {
          name: "DateTime"
        }
      },
      description: {
        serializedName: "properties.description",
        type: {
          name: "String"
        }
      },
      isComposite: {
        serializedName: "properties.isComposite",
        type: {
          name: "Boolean"
        }
      },
      etag: {
        serializedName: "etag",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const PythonPackageCreateParameters: msRest.CompositeMapper = {
  serializedName: "PythonPackageCreateParameters",
  type: {
    name: "Composite",
    className: "PythonPackageCreateParameters",
    modelProperties: {
      contentLink: {
        required: true,
        serializedName: "properties.contentLink",
        type: {
          name: "Composite",
          className: "ContentLink"
        }
      },
      tags: {
        serializedName: "tags",
        type: {
          name: "Dictionary",
          value: {
            type: {
              name: "String"
            }
          }
        }
      }
    }
  }
};

export const PythonPackageUpdateParameters: msRest.CompositeMapper = {
  serializedName: "PythonPackageUpdateParameters",
  type: {
    name: "Composite",
    className: "PythonPackageUpdateParameters",
    modelProperties: {
      tags: {
        serializedName: "tags",
        type: {
          name: "Dictionary",
          value: {
            type: {
              name: "String"
            }
          }
        }
      }
    }
  }
};

export const TypeField: msRest.CompositeMapper = {
  serializedName: "TypeField",
  type: {
    name: "Composite",
    className: "TypeField",
    modelProperties: {
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      type: {
        serializedName: "type",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const TypeFieldListResult: msRest.CompositeMapper = {
  serializedName: "TypeFieldListResult",
  type: {
    name: "Composite",
    className: "TypeFieldListResult",
    modelProperties: {
      value: {
        serializedName: "value",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "TypeField"
            }
          }
        }
      }
    }
  }
};

export const ProxyResource: msRest.CompositeMapper = {
  serializedName: "ProxyResource",
  type: {
    name: "Composite",
    className: "ProxyResource",
    modelProperties: {
      ...Resource.type.modelProperties
    }
  }
};

export const ErrorResponse: msRest.CompositeMapper = {
  serializedName: "ErrorResponse",
  type: {
    name: "Composite",
    className: "ErrorResponse",
    modelProperties: {
      code: {
        serializedName: "code",
        type: {
          name: "String"
        }
      },
      message: {
        serializedName: "message",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const JobStream: msRest.CompositeMapper = {
  serializedName: "JobStream",
  type: {
    name: "Composite",
    className: "JobStream",
    modelProperties: {
      id: {
        serializedName: "id",
        type: {
          name: "String"
        }
      },
      jobStreamId: {
        serializedName: "properties.jobStreamId",
        type: {
          name: "String"
        }
      },
      time: {
        nullable: false,
        serializedName: "properties.time",
        type: {
          name: "DateTime"
        }
      },
      streamType: {
        serializedName: "properties.streamType",
        type: {
          name: "String"
        }
      },
      streamText: {
        serializedName: "properties.streamText",
        type: {
          name: "String"
        }
      },
      summary: {
        serializedName: "properties.summary",
        type: {
          name: "String"
        }
      },
      value: {
        serializedName: "properties.value",
        type: {
          name: "Dictionary",
          value: {
            type: {
              name: "Object"
            }
          }
        }
      }
    }
  }
};

export const RunbookParameter: msRest.CompositeMapper = {
  serializedName: "RunbookParameter",
  type: {
    name: "Composite",
    className: "RunbookParameter",
    modelProperties: {
      type: {
        serializedName: "type",
        type: {
          name: "String"
        }
      },
      isMandatory: {
        serializedName: "isMandatory",
        type: {
          name: "Boolean"
        }
      },
      position: {
        serializedName: "position",
        type: {
          name: "Number"
        }
      },
      defaultValue: {
        serializedName: "defaultValue",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const RunbookDraft: msRest.CompositeMapper = {
  serializedName: "RunbookDraft",
  type: {
    name: "Composite",
    className: "RunbookDraft",
    modelProperties: {
      inEdit: {
        serializedName: "inEdit",
        type: {
          name: "Boolean"
        }
      },
      draftContentLink: {
        serializedName: "draftContentLink",
        type: {
          name: "Composite",
          className: "ContentLink"
        }
      },
      creationTime: {
        nullable: false,
        serializedName: "creationTime",
        type: {
          name: "DateTime"
        }
      },
      lastModifiedTime: {
        nullable: false,
        serializedName: "lastModifiedTime",
        type: {
          name: "DateTime"
        }
      },
      parameters: {
        serializedName: "parameters",
        type: {
          name: "Dictionary",
          value: {
            type: {
              name: "Composite",
              className: "RunbookParameter"
            }
          }
        }
      },
      outputTypes: {
        serializedName: "outputTypes",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "String"
            }
          }
        }
      }
    }
  }
};

export const Runbook: msRest.CompositeMapper = {
  serializedName: "Runbook",
  type: {
    name: "Composite",
    className: "Runbook",
    modelProperties: {
      ...TrackedResource.type.modelProperties,
      runbookType: {
        serializedName: "properties.runbookType",
        type: {
          name: "String"
        }
      },
      publishContentLink: {
        serializedName: "properties.publishContentLink",
        type: {
          name: "Composite",
          className: "ContentLink"
        }
      },
      state: {
        serializedName: "properties.state",
        type: {
          name: "String"
        }
      },
      logVerbose: {
        serializedName: "properties.logVerbose",
        type: {
          name: "Boolean"
        }
      },
      logProgress: {
        serializedName: "properties.logProgress",
        type: {
          name: "Boolean"
        }
      },
      logActivityTrace: {
        serializedName: "properties.logActivityTrace",
        type: {
          name: "Number"
        }
      },
      jobCount: {
        serializedName: "properties.jobCount",
        type: {
          name: "Number"
        }
      },
      parameters: {
        serializedName: "properties.parameters",
        type: {
          name: "Dictionary",
          value: {
            type: {
              name: "Composite",
              className: "RunbookParameter"
            }
          }
        }
      },
      outputTypes: {
        serializedName: "properties.outputTypes",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "String"
            }
          }
        }
      },
      draft: {
        serializedName: "properties.draft",
        type: {
          name: "Composite",
          className: "RunbookDraft"
        }
      },
      provisioningState: {
        serializedName: "properties.provisioningState",
        type: {
          name: "Enum",
          allowedValues: [
            "Succeeded"
          ]
        }
      },
      lastModifiedBy: {
        serializedName: "properties.lastModifiedBy",
        type: {
          name: "String"
        }
      },
      creationTime: {
        nullable: false,
        serializedName: "properties.creationTime",
        type: {
          name: "DateTime"
        }
      },
      lastModifiedTime: {
        nullable: false,
        serializedName: "properties.lastModifiedTime",
        type: {
          name: "DateTime"
        }
      },
      description: {
        serializedName: "properties.description",
        type: {
          name: "String"
        }
      },
      etag: {
        serializedName: "etag",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const RunbookCreateOrUpdateParameters: msRest.CompositeMapper = {
  serializedName: "RunbookCreateOrUpdateParameters",
  type: {
    name: "Composite",
    className: "RunbookCreateOrUpdateParameters",
    modelProperties: {
      logVerbose: {
        serializedName: "properties.logVerbose",
        type: {
          name: "Boolean"
        }
      },
      logProgress: {
        serializedName: "properties.logProgress",
        type: {
          name: "Boolean"
        }
      },
      runbookType: {
        required: true,
        serializedName: "properties.runbookType",
        type: {
          name: "String"
        }
      },
      draft: {
        serializedName: "properties.draft",
        type: {
          name: "Composite",
          className: "RunbookDraft"
        }
      },
      publishContentLink: {
        serializedName: "properties.publishContentLink",
        type: {
          name: "Composite",
          className: "ContentLink"
        }
      },
      description: {
        serializedName: "properties.description",
        type: {
          name: "String"
        }
      },
      logActivityTrace: {
        serializedName: "properties.logActivityTrace",
        type: {
          name: "Number"
        }
      },
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      location: {
        serializedName: "location",
        type: {
          name: "String"
        }
      },
      tags: {
        serializedName: "tags",
        type: {
          name: "Dictionary",
          value: {
            type: {
              name: "String"
            }
          }
        }
      }
    }
  }
};

export const RunbookUpdateParameters: msRest.CompositeMapper = {
  serializedName: "RunbookUpdateParameters",
  type: {
    name: "Composite",
    className: "RunbookUpdateParameters",
    modelProperties: {
      description: {
        serializedName: "properties.description",
        type: {
          name: "String"
        }
      },
      logVerbose: {
        serializedName: "properties.logVerbose",
        type: {
          name: "Boolean"
        }
      },
      logProgress: {
        serializedName: "properties.logProgress",
        type: {
          name: "Boolean"
        }
      },
      logActivityTrace: {
        serializedName: "properties.logActivityTrace",
        type: {
          name: "Number"
        }
      },
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      location: {
        serializedName: "location",
        type: {
          name: "String"
        }
      },
      tags: {
        serializedName: "tags",
        type: {
          name: "Dictionary",
          value: {
            type: {
              name: "String"
            }
          }
        }
      }
    }
  }
};

export const RunbookDraftUndoEditResult: msRest.CompositeMapper = {
  serializedName: "RunbookDraftUndoEditResult",
  type: {
    name: "Composite",
    className: "RunbookDraftUndoEditResult",
    modelProperties: {
      statusCode: {
        serializedName: "statusCode",
        type: {
          name: "String"
        }
      },
      requestId: {
        serializedName: "requestId",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const TestJobCreateParameters: msRest.CompositeMapper = {
  serializedName: "TestJobCreateParameters",
  type: {
    name: "Composite",
    className: "TestJobCreateParameters",
    modelProperties: {
      parameters: {
        serializedName: "parameters",
        type: {
          name: "Dictionary",
          value: {
            type: {
              name: "String"
            }
          }
        }
      },
      runOn: {
        serializedName: "runOn",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const TestJob: msRest.CompositeMapper = {
  serializedName: "TestJob",
  type: {
    name: "Composite",
    className: "TestJob",
    modelProperties: {
      creationTime: {
        nullable: false,
        serializedName: "creationTime",
        type: {
          name: "DateTime"
        }
      },
      status: {
        serializedName: "status",
        type: {
          name: "String"
        }
      },
      statusDetails: {
        serializedName: "statusDetails",
        type: {
          name: "String"
        }
      },
      runOn: {
        serializedName: "runOn",
        type: {
          name: "String"
        }
      },
      startTime: {
        nullable: true,
        serializedName: "startTime",
        type: {
          name: "DateTime"
        }
      },
      endTime: {
        nullable: true,
        serializedName: "endTime",
        type: {
          name: "DateTime"
        }
      },
      exception: {
        serializedName: "exception",
        type: {
          name: "String"
        }
      },
      lastModifiedTime: {
        nullable: false,
        serializedName: "lastModifiedTime",
        type: {
          name: "DateTime"
        }
      },
      lastStatusModifiedTime: {
        nullable: true,
        serializedName: "lastStatusModifiedTime",
        type: {
          name: "DateTime"
        }
      },
      parameters: {
        serializedName: "parameters",
        type: {
          name: "Dictionary",
          value: {
            type: {
              name: "String"
            }
          }
        }
      },
      logActivityTrace: {
        serializedName: "logActivityTrace",
        type: {
          name: "Number"
        }
      }
    }
  }
};

export const RunbookCreateOrUpdateDraftProperties: msRest.CompositeMapper = {
  serializedName: "RunbookCreateOrUpdateDraftProperties",
  type: {
    name: "Composite",
    className: "RunbookCreateOrUpdateDraftProperties",
    modelProperties: {
      logVerbose: {
        serializedName: "logVerbose",
        type: {
          name: "Boolean"
        }
      },
      logProgress: {
        serializedName: "logProgress",
        type: {
          name: "Boolean"
        }
      },
      runbookType: {
        required: true,
        serializedName: "runbookType",
        type: {
          name: "String"
        }
      },
      draft: {
        required: true,
        serializedName: "draft",
        type: {
          name: "Composite",
          className: "RunbookDraft"
        }
      },
      description: {
        serializedName: "description",
        type: {
          name: "String"
        }
      },
      logActivityTrace: {
        serializedName: "logActivityTrace",
        type: {
          name: "Number"
        }
      }
    }
  }
};

export const RunbookCreateOrUpdateDraftParameters: msRest.CompositeMapper = {
  serializedName: "RunbookCreateOrUpdateDraftParameters",
  type: {
    name: "Composite",
    className: "RunbookCreateOrUpdateDraftParameters",
    modelProperties: {
      runbookContent: {
        required: true,
        serializedName: "runbookContent",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const RunbookDraftReplaceContentHeaders: msRest.CompositeMapper = {
  serializedName: "runbookdraft-replacecontent-headers",
  type: {
    name: "Composite",
    className: "RunbookDraftReplaceContentHeaders",
    modelProperties: {
      location: {
        serializedName: "location",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const RunbookPublishHeaders: msRest.CompositeMapper = {
  serializedName: "runbook-publish-headers",
  type: {
    name: "Composite",
    className: "RunbookPublishHeaders",
    modelProperties: {
      location: {
        serializedName: "location",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const ModuleListResult: msRest.CompositeMapper = {
  serializedName: "ModuleListResult",
  type: {
    name: "Composite",
    className: "ModuleListResult",
    modelProperties: {
      value: {
        serializedName: "",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "Module"
            }
          }
        }
      },
      nextLink: {
        serializedName: "nextLink",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const RunbookListResult: msRest.CompositeMapper = {
  serializedName: "RunbookListResult",
  type: {
    name: "Composite",
    className: "RunbookListResult",
    modelProperties: {
      value: {
        serializedName: "",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "Runbook"
            }
          }
        }
      },
      nextLink: {
        serializedName: "nextLink",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const JobStreamListResult: msRest.CompositeMapper = {
  serializedName: "JobStreamListResult",
  type: {
    name: "Composite",
    className: "JobStreamListResult",
    modelProperties: {
      value: {
        serializedName: "",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "JobStream"
            }
          }
        }
      },
      nextLink: {
        serializedName: "nextLink",
        type: {
          name: "String"
        }
      }
    }
  }
};
